const fixedAssets = {
    frontendRoutes: ['/inventory/fixed-assets', '/inventory/allocations', '/reports/expense-asset'],
    description: 'Fixed assets and depreciation tracking',
    form: 'FixedAssetForm',
    tableName: 'fixed_assets',
    displayName: 'Fixed Assets',
    icon: 'Package',
    defaultSort: { field: 'purchase_date', direction: 'DESC' },
    defaultFilters: { condition_status: ['new', 'good', 'fair'] },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'category_id',
        defaultMetric: 'purchase_cost',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'purchase_cost', 'current_value', 'depreciation_total', 'asset_age'],
        availableDimensions: ['category_id', 'location_id', 'assigned_to_user_id', 'condition_status'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        asset_tag: {
            label: 'Asset Tag',
            placeholder: 'AST-001',
            type: 'text',
            required: true,
            description: 'Unique asset identifier tag',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        serial_number: {
            label: 'Serial Number',
            placeholder: 'SN-001',
            type: 'text',
            description: 'Manufacturer serial number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        sku_id: {
            label: 'SKU',
            placeholder: 'Select SKU',
            type: 'select',
            required: true,
            options: 'skus',
            description: 'SKU of the asset',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'skus',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'sku',
        },
        asset_name: {
            label: 'Asset Name',
            placeholder: 'Dell Laptop',
            type: 'text',
            required: true,
            description: 'Name/description of the asset',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'asset',
        },
        description: {
            label: 'Description',
            placeholder: 'Asset description',
            type: 'textarea',
            description: 'Detailed asset description',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        purchase_date: {
            label: 'Purchase Date',
            type: 'date',
            required: true,
            description: 'Date the asset was purchased',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        purchase_cost: {
            label: 'Purchase Cost',
            placeholder: '0.00',
            type: 'number',
            required: true,
            description: 'Original purchase cost',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Cost cannot be negative',
            },
        },
        salvage_value: {
            label: 'Salvage Value',
            placeholder: '0.00',
            type: 'number',
            description: 'Estimated salvage value at end of life',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Salvage value cannot be negative',
            },
        },
        depreciation_method: {
            label: 'Depreciation Method',
            placeholder: 'Select method',
            type: 'select',
            options: 'depreciation_methods',
            description: 'Depreciation calculation method',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'depreciation_methods',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'depreciation',
        },
        useful_life_years: {
            label: 'Useful Life (Years)',
            placeholder: '5',
            type: 'number',
            required: true,
            description: 'Estimated useful life in years',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'asset_life',
            validation: {
                minValue: 0,
                message: 'Useful life must be positive',
            },
        },
        current_value: {
            label: 'Current Value',
            placeholder: '0.00',
            type: 'number',
            disabled: true,
            description: 'Current book value after depreciation',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
        },
        accumulated_depreciation: {
            label: 'Accumulated Depreciation',
            placeholder: '0.00',
            type: 'number',
            disabled: true,
            description: 'Total depreciation to date',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
        },
        location_id: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            options: 'locations',
            description: 'Current location of the asset',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        assigned_to_user_id: {
            label: 'Assigned To',
            placeholder: 'Select user',
            type: 'select',
            options: 'users',
            description: 'User the asset is assigned to',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'assignment',
        },
        condition_status: {
            label: 'Condition Status',
            placeholder: 'Select condition',
            type: 'select',
            options: 'conditions',
            description: 'Current condition of the asset',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'conditions',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'condition',
        },
        warranty_expiry: {
            label: 'Warranty Expiry',
            type: 'date',
            description: 'Date warranty expires',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'warranty',
        },
        insurance_policy_number: {
            label: 'Insurance Policy Number',
            placeholder: 'POL-001',
            type: 'text',
            description: 'Insurance policy reference',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        disposal_date: {
            label: 'Disposal Date',
            type: 'date',
            description: 'Date the asset was disposed',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        disposal_value: {
            label: 'Disposal Value',
            placeholder: '0.00',
            type: 'number',
            description: 'Value received on disposal',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
        },
        grn_item_id: {
            label: 'GRN Item',
            placeholder: 'Select GRN item',
            type: 'select',
            options: 'grn_items',
            description: 'Associated GRN item if applicable',
            showInTable: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'grn_items',
            analyzable: false,
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default fixedAssets;