const adminAccounts = {
    frontendRoutes: ['/settings/profile'],
    description: 'Root tenant accounts for multi-company SaaS setup',
    form: 'AdminAccountForm',
    tableName: 'admin_accounts',
    displayName: 'Admin Accounts',
    icon: 'Building',
    defaultSort: { field: 'company_name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'subscription_plan',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'active_count', 'by_plan', 'by_status'],
        availableDimensions: ['subscription_plan', 'subscription_status', 'is_active'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        account_code: {
            label: 'Account Code',
            placeholder: 'ACC-001',
            type: 'text',
            disabled: true,
            description: 'Unique account identifier',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        company_name: {
            label: 'Company Name',
            placeholder: 'Acme Corporation',
            type: 'text',
            required: true,
            description: 'Company/tenant name',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'company',
        },
        company_registration_number: {
            label: 'Registration Number',
            placeholder: 'RC123456',
            type: 'text',
            description: 'Company registration number',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        tax_id: {
            label: 'Tax ID',
            placeholder: 'TIN-123-456-789',
            type: 'text',
            description: 'Company tax identification number',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        billing_email: {
            label: 'Billing Email',
            placeholder: 'billing@company.com',
            type: 'email',
            required: true,
            description: 'Email for billing communications',
            icon: 'EnvelopeIcon',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
            validation: {
                pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                message: 'Please enter a valid email address',
            },
        },
        billing_phone: {
            label: 'Billing Phone',
            placeholder: '+1 (555) 000-0000',
            type: 'phone',
            description: 'Phone for billing communications',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        billing_address: {
            label: 'Billing Address',
            placeholder: '123 Corporate Blvd',
            type: 'textarea',
            description: 'Billing address',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        subscription_plan: {
            label: 'Subscription Plan',
            placeholder: 'Select plan',
            type: 'select',
            options: 'subscription_plans',
            description: 'Current subscription plan',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'subscription_plans',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'plan',
        },
        subscription_status: {
            label: 'Subscription Status',
            placeholder: 'Select status',
            type: 'select',
            options: 'subscription_statuses',
            description: 'Current subscription status',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'subscription_statuses',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        subscription_start_date: {
            label: 'Subscription Start Date',
            type: 'date',
            description: 'When subscription started',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        subscription_end_date: {
            label: 'Subscription End Date',
            type: 'date',
            description: 'When subscription expires',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        max_users: {
            label: 'Max Users',
            placeholder: '10',
            type: 'number',
            description: 'Maximum number of users allowed',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'limits',
            validation: {
                minValue: 1,
                message: 'Max users must be at least 1',
            },
        },
        max_storage_gb: {
            label: 'Max Storage (GB)',
            placeholder: '5',
            type: 'number',
            description: 'Maximum storage in GB',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'limits',
            validation: {
                minValue: 0,
                message: 'Storage cannot be negative',
            },
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            description: 'Whether the account is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        is_verified: {
            label: 'Verified',
            type: 'toggle',
            default: false,
            description: 'Whether the account is verified',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        is_database_created: {
            label: 'Database Created',
            type: 'toggle',
            disabled: true,
            description: 'Whether tenant database has been created',
            showInTable: false,
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: false,
        },
        billing_cycle: {
            label: 'Billing Cycle',
            placeholder: 'Select cycle',
            type: 'select',
            options: 'billing_cycles',
            description: 'Billing cycle frequency',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'billing_cycles',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'billing',
        },
        account_balance: {
            label: 'Account Balance',
            placeholder: '0.00',
            type: 'number',
            disabled: true,
            description: 'Current account balance',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default adminAccounts;