const approvalWorkflows = {
    frontendRoutes: ['/procurement/approvals', '/settings/workflows'],
    description: 'Defines approval workflow templates',
    form: 'ApprovalWorkflowForm',
    tableName: 'approval_workflows',
    displayName: 'Approval Workflows',
    icon: 'GitBranch',
    defaultSort: { field: 'workflow_name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'entity_type',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table'],
        availableMetrics: ['count', 'avg_approval_steps', 'total_workflows'],
        availableDimensions: ['entity_type', 'is_active'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        workflow_name: {
            label: 'Workflow Name',
            placeholder: 'Purchase Approval',
            type: 'text',
            required: true,
            description: 'Name of the workflow',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'workflow',
        },
        workflow_description: {
            label: 'Description',
            placeholder: 'Workflow description',
            type: 'textarea',
            description: 'Detailed description of the workflow',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        entity_type: {
            label: 'Entity Type',
            placeholder: 'Select entity type',
            type: 'select',
            required: true,
            options: 'entity_types',
            description: 'Type of entity this workflow applies to',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'entity_types',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'entity',
        },
        min_amount: {
            label: 'Min Amount',
            placeholder: '0.00',
            type: 'number',
            description: 'Minimum amount for this workflow',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'min',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Min amount cannot be negative',
            },
        },
        max_amount: {
            label: 'Max Amount',
            placeholder: '0.00',
            type: 'number',
            description: 'Maximum amount for this workflow',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'max',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Max amount cannot be negative',
            },
        },
        is_system_workflow: {
            label: 'System Workflow',
            type: 'toggle',
            default: false,
            hidden: true,
            description: 'Internal system workflow flag',
            showInTable: false,
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: false,
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            description: 'Whether the workflow is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default approvalWorkflows;