const auditTrail = {
    frontendRoutes: ['/reports/audit'],
    description: 'Audit trail for all system actions',
    form: null,
    tableName: 'audit_trail',
    displayName: 'Audit Trail',
    icon: 'Clock',
    defaultSort: { field: 'action_timestamp', direction: 'DESC' },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'action_type',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'action_count', 'user_activity'],
        availableDimensions: ['action_type', 'entity_type', 'user_id', 'action_timestamp'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        user_id: {
            label: 'User',
            placeholder: 'Select user',
            type: 'select',
            options: 'users',
            description: 'User who performed the action',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'user',
        },
        action_type: {
            label: 'Action Type',
            placeholder: 'Select action',
            type: 'select',
            options: 'audit_actions',
            description: 'Type of action performed',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'audit_actions',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'action',
        },
        entity_type: {
            label: 'Entity Type',
            placeholder: 'Select entity',
            type: 'text',
            description: 'Type of entity affected',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'entity',
        },
        entity_id: {
            label: 'Entity ID',
            placeholder: '1',
            type: 'number',
            description: 'ID of the entity affected',
            showInTable: true,
            tableWidth: '80px',
            filterable: true,
            filterType: 'number',
            analyzable: false,
        },
        old_values: {
            label: 'Old Values',
            type: 'json',
            disabled: true,
            description: 'Previous values before change',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        new_values: {
            label: 'New Values',
            type: 'json',
            disabled: true,
            description: 'New values after change',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        ip_address: {
            label: 'IP Address',
            placeholder: '192.168.1.1',
            type: 'text',
            disabled: true,
            description: 'IP address of the user',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        user_agent: {
            label: 'User Agent',
            type: 'text',
            disabled: true,
            description: 'Browser/device information',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        session_id: {
            label: 'Session ID',
            type: 'text',
            disabled: true,
            description: 'Session identifier',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        action_timestamp: {
            label: 'Action Timestamp',
            type: 'datetime',
            disabled: true,
            description: 'When the action occurred',
            showInTable: true,
            tableWidth: '180px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
    },
};

export default auditTrail;