// src/config/purchaseCashtransfers.js

const cashtransfers = {
    frontendRoutes: ['/procurement/cashtransfers'],
    description: 'Purchase cashtransfers initiated by employees',
    form: 'CashtransferForm',
    tableName: 'cashtransfers',
    displayName: 'Cash Transfers',
    icon: 'ShoppingCart',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: 'pending_approval' },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'department_id',
        defaultMetric: 'total_amount',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'total_amount', 'avg_amount', 'pending_count', 'approved_count'],
        availableDimensions: ['department_id', 'cashtransfer_type', 'status', 'priority', 'created_at'],
    },
    fields: {
        id: {
            label: 'PR Number',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Auto-generated purchase cashtransfer number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        title: {
            label: 'Title',
            placeholder: 'Office Supplies Purchase',
            type: 'text',
            required: true,
            description: 'Brief title of the cashtransfer',
            showInTable: true,
            showInForm: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'title',
        },
        description: {
            label: 'Description',
            placeholder: 'Detailed description of cash transfer',
            type: 'textarea',
            description: 'Detailed description of the cash transfer',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
        budget_id: {
            label: 'Budget',
            placeholder: 'Select budget',
            type: 'select',
            options: 'budgets',
            description: 'Budget making the request',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'budgets',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'budget',
            nameField: 'budget_name',
        },
        budget_name: {
            label: 'Budget Name',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Budget name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'budget',
        },
        requester_id: {
            label: 'Requester',
            placeholder: 'Select requester',
            type: 'select',
            hidden: true,
            options: 'users',
            description: 'Employee requesting the purchase',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
            nameField: 'requester_name',
        },
        requester_name: {
            label: 'Requester Name',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Requester full name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
        },
        department_id: {
            label: 'Department',
            placeholder: 'Select department',
            type: 'select',
            required: true,
            options: 'departments',
            description: 'Department making the request',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'departments',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
            nameField: 'department_name',
        },
        department_name: {
            label: 'Department Name',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Department name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        vendor_id: {
            label: 'Vendor',
            placeholder: 'Select vendor',
            type: 'select',
            hidden:true,
            options: 'vendors',
            description: 'Preferred vendor for this request',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'vendors',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
            nameField: 'vendor_name',
        },
        vendor_name: {
            label: 'Vendor Name',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Vendor name',
            showInTable: false,
            showInForm: false, // ✅ Explicitly set to false
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
        },
        location_id: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            hidden: true,
            options: 'locations',
            description: 'Location where items will be delivered',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
            nameField: 'location_name',
        },
        location_name: {
            label: 'Location Name',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Location name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        cashtransfer_type: {
            label: 'Cashtransfer Type',
            placeholder: 'Select type',
            type: 'select',
            required: true,
            hidden: true,
            options: 'cashtransfer_types',
            description: 'Type of cashtransfer ',
            showInTable: true,
            showInForm: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'cashtransfer_types',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'type',
        },
        total_amount: {
            label: 'Total Amount',
            placeholder: '0.00',
            hidden: true,
            type: 'number',
            description: 'Total estimated amount',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: function(value) {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Amount cannot be negative',
            },
        },
        currency_id: {
            label: 'Currency',
            placeholder: 'USD',
            type: 'select',
            options: 'currencies',
            default: 'USD',
            description: 'Currency for the transaction',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        currency_name: {
            label: 'Currency',
            placeholder: 'NGR',
            hidden: false,
            type: 'select',
            options: 'currencies',
            default: 'NGR',
            description: 'Currency for the transaction',
            showInTable: false,
            showInForm: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        is_capex: {
            label: 'Is CAPEX?',
            hidden:true,
            type: 'select',
            options: 'yes_no',
            default: false,
            description: 'Whether this is a capital expenditure',
            showInTable: true,
            showInForm: true,
            tableWidth: '100px',
            tableFormat: function(value) {
                return value ? '✅' : '❌';
            },
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'capex',
        },
        priority: {
            label: 'Priority',
            placeholder: 'Select priority',
            type: 'select',
            options: 'priorities',
            description: 'Priority level of the request',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'priorities',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'priority',
        },
        priority_name: {
            label: 'Priority',
            placeholder: 'Select priority',
            type: 'select',
            options: 'priorities',
            description: 'Priority level of the request',
            showInTable: true,
            showInForm: false,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'priorities',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'priority',
        },
        status: {
            label: 'Status',
            placeholder: 'draft',
            type: 'select',
            options: 'cashtransfer_status',
            description: 'Current status of the cashtransfer',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'cashtransfer_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        status_name: {
            label: 'Status',
            placeholder: 'draft',
            type: 'select',
            options: 'cashtransfer_status',
            disabled: true,
            description: 'Current status of the cashtransfer',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'cashtransfer_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        approver_id: {
            label: 'Approver',
            placeholder: 'Select approver',
            hidden: true,
            type: 'select',
            options: 'users',
            description: 'Person who approved this cashtransfer',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
            nameField: 'approver_name',
        },
        approver_name: {
            label: 'Approver Name',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Approver full name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        approve_date: {
            label: 'Approval Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            description: 'Date when the cashtransfer was approved',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        approval_workflow_id: {
            label: 'Approval Workflow',
            placeholder: 'Select workflow',
            hidden:true,
            type: 'select',
            options: 'approval_workflows',
            description: 'Approval workflow to follow',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'approval_workflows',
            analyzable: false,
            nameField: 'approval_workflow_name',
        },
        approval_workflow_name: {
            label: 'Workflow Name',
            type: 'text',
            hidden:true,
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Approval workflow name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            filterable: false,
            analyzable: false,
        },
        current_approval_level: {
            label: 'Current Approval Level',
            type: 'number',
            disabled: true,
            hidden: true,
            description: 'Current step in approval workflow',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'approval',
        },
        expected_delivery_date: {
            label: 'Expected Delivery Date',
            type: 'date',
            description: 'Expected delivery date',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
         created_at: {
            label: 'Created Date',
            type: 'date',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        created_by_id: {
            label: 'Created By',
            type: 'select',
            options: 'users',
            hidden: true,
            disabled: true,
            description: 'User who created this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
            nameField: 'created_by_name',
        },
        created_by_name: {
            label: 'Created By',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Creator full name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        notes: {
            label: 'Notes',
            placeholder: 'Additional notes',
            type: 'textarea',
            description: 'Additional notes or comments',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
       
        updated_at: {
            label: 'Updated Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        updated_by_id: {
            label: 'Updated By',
            type: 'select',
            options: 'users',
            disabled: true,
            hidden: true,
            description: 'User who last updated this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
            nameField: 'updated_by_name',
        },
        updated_by_name: {
            label: 'Updated By',
            type: 'text',
            hidden: false, // ✅ Changed from true to false
            disabled: true,
            description: 'Updater full name',
            showInTable: true,
            showInForm: false, // ✅ Explicitly set to false
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
        },
    },
};

export default cashtransfers;