const cashadvances = {
    frontendRoutes: ['/procurement/cashadvances'],
    description: 'Manage employee cash advance requests for procurement and business-related expenses. This module handles the request, approval, and tracking of cash advances issued to employees for official purposes, including travel, purchases, and other business expenses.',
    form: 'CashadvanceForm',
    tableName: 'cashadvances',
    displayName: 'Cash Advance Requests',
    icon: 'ShoppingCart',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: 'pending_approval' },
    
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'department_id',
        defaultMetric: 'total_amount',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'total_amount', 'avg_amount', 'pending_count', 'approved_count'],
        availableDimensions: ['department_id', 'cashadvance_type', 'status', 'priority', 'created_at'],
    },
    
    fields: {
        id: {
            label: 'Cash Advance Reference',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Auto-generated unique reference number for this cash advance request',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        
        title: {
            label: 'Request Title',
            placeholder: 'e.g., Travel Advance for Lagos Trip, Office Supplies Purchase',
            type: 'text',
            required: true,
            description: 'A clear title describing the purpose of this cash advance request',
            showInTable: true,
            showInForm: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'title',
        },
        
        description: {
            label: 'Request Description',
            placeholder: 'Provide detailed information about why this cash advance is needed, including purpose, expected use, and any relevant details...',
            type: 'textarea',
            description: 'Detailed description of the cash advance request, including purpose and justification',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
        
        budget_id: {
            label: 'Budget Source',
            placeholder: 'Select budget',
            type: 'select',
            options: 'budgets',
            description: 'Budget line item that this cash advance will be charged against',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'budgets',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'budget',
            nameField: 'budget_name',
        },
        
        budget_name: {
            label: 'Budget Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Budget name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'budget',
        },
        
        requester_id: {
            label: 'Requester',
            placeholder: 'Select requester',
            type: 'select',
            hidden: true,
            options: 'users',
            description: 'Employee requesting this cash advance',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
            nameField: 'requester_name',
        },
        
        requester_name: {
            label: 'Requester Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the employee requesting this cash advance',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
        },
        
        department_id: {
            label: 'Department',
            placeholder: 'Select department',
            type: 'select',
            required: true,
            options: 'departments',
            description: 'Department making this cash advance request',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'departments',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
            nameField: 'department_name',
        },
        
        department_name: {
            label: 'Department Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Department name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        
        vendor_id: {
            label: 'Vendor (if applicable)',
            placeholder: 'Select vendor',
            type: 'select',
            hidden: true,
            options: 'vendors',
            description: 'Preferred vendor for this purchase (if cash advance is for vendor payment)',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'vendors',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
            nameField: 'vendor_name',
        },
        
        vendor_name: {
            label: 'Vendor Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Vendor name',
            showInTable: false,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
        },
        
        location_id: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            hidden: true,
            options: 'locations',
            description: 'Location where the cash advance will be used or where expenses will be incurred',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
            nameField: 'location_name',
        },
        
        location_name: {
            label: 'Location Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Location name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        
        total_amount: {
            label: 'Total Amount Requested',
            placeholder: '0.00',
            hidden: true,
            type: 'number',
            description: 'Total amount of cash advance being requested',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableAlign: 'right',
           
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Amount cannot be negative',
            },
        },
        
        currency_id: {
            label: 'Currency',
            placeholder: 'USD',
            type: 'select',
            options: 'currencies',
            default: 'USD',
            description: 'Currency for this cash advance transaction',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        
        currency_name: {
            label: 'Currency',
            placeholder: 'NGR',
            hidden: false,
            type: 'select',
            options: 'currencies',
            default: 'NGR',
            description: 'Currency for this cash advance transaction',
            showInTable: false,
            showInForm: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
       
        priority: {
            label: 'Priority',
            placeholder: 'Select priority level',
            type: 'select',
            options: 'priorities',
            description: 'Priority level of this cash advance request (Low, Normal, High, Urgent)',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'priorities',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'priority',
        },
        
        priority_name: {
            label: 'Priority',
            placeholder: 'Select priority',
            type: 'select',
            options: 'priorities',
            description: 'Priority level of this cash advance request',
            showInTable: true,
            showInForm: false,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'priorities',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'priority',
        },
        
        status: {
            label: 'Status',
            placeholder: 'Select status',
            type: 'select',
            options: 'cashadvance_status',
            description: 'Current status of this cash advance request',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'cashadvance_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        
        status_name: {
            label: 'Status',
            placeholder: 'Select status',
            type: 'select',
            options: 'cashadvance_status',
            disabled: true,
            description: 'Current status of this cash advance request',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'cashadvance_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        
        approver_id: {
            label: 'Approver',
            placeholder: 'Select approver',
            hidden: true,
            type: 'select',
            options: 'users',
            description: 'Person who approved or will approve this cash advance',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
            nameField: 'approver_name',
        },
        
        approver_name: {
            label: 'Approver Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who approved this cash advance',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        
        approve_date: {
            label: 'Approval Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            description: 'Date and time when this cash advance was approved',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        
        approval_workflow_id: {
            label: 'Approval Workflow',
            placeholder: 'Select approval workflow',
            hidden: true,
            type: 'select',
            options: 'approval_workflows',
            description: 'The approval workflow assigned to this cash advance request',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'approval_workflows',
            analyzable: false,
            nameField: 'approval_workflow_name',
        },
        
        approval_workflow_name: {
            label: 'Workflow Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Approval workflow name',
            showInTable: true,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        
        current_approval_level: {
            label: 'Current Approval Level',
            type: 'number',
            disabled: true,
            hidden: true,
            description: 'Current step in the approval workflow',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'approval',
        },
        
        expected_delivery_date: {
            label: 'Expected Completion Date',
            type: 'date',
            description: 'Expected date when the cash advance will be utilized and settled',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        
        created_at: {
            label: 'Created Date',
            type: 'date',
            description: 'Date when this cash advance request was created',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        
        created_by_id: {
            label: 'Created By',
            type: 'select',
            options: 'users',
            hidden: true,
            disabled: true,
            description: 'User who created this cash advance record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
            nameField: 'created_by_name',
        },
        
        created_by_name: {
            label: 'Created By',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who created this record',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        
        notes: {
            label: 'Notes',
            placeholder: 'Add any additional information, special instructions, or supporting details...',
            type: 'textarea',
            description: 'Additional notes, special instructions, or supporting information for this cash advance request',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
       
        updated_at: {
            label: 'Updated Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        
        updated_by_id: {
            label: 'Updated By',
            type: 'select',
            options: 'users',
            disabled: true,
            hidden: true,
            description: 'User who last updated this cash advance record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
            nameField: 'updated_by_name',
        },
        
        updated_by_name: {
            label: 'Updated By',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who last updated this record',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
        },
    },
};

export default cashadvances;