const chartOfAccounts = {
    frontendRoutes: ['/finance/opex', '/reports/expense-asset', '/settings/chart-of-accounts'],
    description: 'Chart of Accounts for financial reporting',
    form: 'ChartOfAccountForm',
    tableName: 'chart_of_accounts',
    displayName: 'Chart of Accounts',
    icon: 'BookOpen',
    defaultSort: { field: 'account_code', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'account_type',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table'],
        availableMetrics: ['count', 'active_count', 'by_type'],
        availableDimensions: ['account_type', 'category', 'is_active'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        account_code: {
            label: 'Account Code',
            placeholder: '1000',
            type: 'text',
            required: true,
            description: 'Unique account code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        account_name: {
            label: 'Account Name',
            placeholder: 'Cash - Operating',
            type: 'text',
            required: true,
            description: 'Name of the account',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'account',
        },
        account_type: {
            label: 'Account Type',
            placeholder: 'Select type',
            type: 'select',
            required: true,
            options: 'account_types',
            description: 'Type of account (asset/liability/equity/income/expense)',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'account_types',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'type',
        },
        category: {
            label: 'Category',
            placeholder: 'Current Assets',
            type: 'text',
            description: 'Category within account type',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'category',
        },
        sub_category: {
            label: 'Sub Category',
            placeholder: 'Cash',
            type: 'text',
            description: 'Sub-category for more detailed classification',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'sub_category',
        },
        is_system_account: {
            label: 'System Account',
            type: 'toggle',
            default: false,
            hidden: true,
            description: 'Internal system account flag',
            showInTable: false,
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: false,
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            description: 'Whether the account is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default chartOfAccounts;