const grns = {
    frontendRoutes: ['/inventory/grn'],
    description: 'Goods Received Notes for incoming inventory',
    form: 'GRNForm',
    tableName: 'grns',
    displayName: 'Goods Received Notes',
    icon: 'PackageCheck',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: ['pending_review', 'approved'] },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'vendor_id',
        defaultMetric: 'total_amount',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'total_amount', 'avg_amount', 'total_quantity'],
        availableDimensions: ['vendor_id', 'status', 'created_at'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grn_number: {
            label: 'GRN Number',
            placeholder: 'GRN-2026-001',
            type: 'text',
            disabled: true,
            description: 'Auto-generated goods received note number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        po_id: {
            label: 'Purchase Order',
            placeholder: 'Select PO',
            type: 'select',
            required: true,
            options: 'purchase_orders',
            description: 'Purchase order being fulfilled',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'purchase_orders',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'po',
        },
        vendor_id: {
            label: 'Vendor',
            placeholder: 'Select vendor',
            type: 'select',
            required: true,
            options: 'vendors',
            description: 'Vendor delivering the goods',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'vendors',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
        },
        received_by: {
            label: 'Received By',
            placeholder: 'Select user',
            type: 'select',
            required: true,
            options: 'users',
            description: 'User who received the goods',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'receiver',
        },
        location_id: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            options: 'locations',
            description: 'Location where goods were received',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        delivery_note_number: {
            label: 'Delivery Note Number',
            placeholder: 'DN-001',
            type: 'text',
            description: 'Vendor delivery note number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        invoice_number: {
            label: 'Invoice Number',
            placeholder: 'INV-001',
            type: 'text',
            description: 'Vendor invoice number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        receipt_date: {
            label: 'Receipt Date',
            type: 'date',
            required: true,
            description: 'Date goods were received',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        total_quantity_received: {
            label: 'Total Quantity Received',
            placeholder: '0',
            type: 'number',
            description: 'Total quantity of items received',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'quantity',
            validation: {
                minValue: 0,
                message: 'Quantity cannot be negative',
            },
        },
        total_amount: {
            label: 'Total Amount',
            placeholder: '0.00',
            type: 'number',
            description: 'Total value of goods received',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Amount cannot be negative',
            },
        },
        is_fully_received: {
            label: 'Fully Received',
            type: 'toggle',
            disabled: true,
            description: 'Whether all items from PO were received',
            showInTable: true,
            tableWidth: '100px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        status: {
            label: 'Status',
            placeholder: 'draft',
            type: 'select',
            options: 'grn_status',
            disabled: true,
            description: 'Current GRN status',
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                const statuses = {
                    draft: 'Draft',
                    pending_review: 'Pending Review',
                    approved: 'Approved',
                    rejected: 'Rejected',
                    partially_approved: 'Partially Approved',
                };
                return statuses[value] || value;
            },
            filterable: true,
            filterType: 'select',
            filterOptions: 'grn_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        notes: {
            label: 'Notes',
            placeholder: 'Additional notes',
            type: 'textarea',
            description: 'Additional notes about the receipt',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default grns;