// src/config/purchaseIncomes.js

const incomes = {
    frontendRoutes: ['/procurement/incomes'],
    description: 'Record and manage all income and sales revenue generated from procurement activities, including sales of goods, services, and other revenue streams. This module helps track financial performance and monitor revenue collection across departments and locations.',
    form: 'IncomeForm',
    tableName: 'incomes',
    displayName: 'Income & Sales Revenue',
    icon: 'ShoppingCart',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: 'pending_approval' },
    
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'department_id',
        defaultMetric: 'total_amount',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'total_amount', 'avg_amount', 'pending_count', 'approved_count'],
        availableDimensions: ['department_id', 'income_type', 'status', 'priority', 'created_at'],
    },
    
    fields: {
        id: {
            label: 'Income Reference',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Auto-generated unique reference number for this income record',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        
        title: {
            label: 'Income Title',
            placeholder: 'e.g., Q1 2024 Sales Revenue',
            type: 'text',
            required: true,
            description: 'A clear title that identifies this income source and period',
            showInTable: true,
            showInForm: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'title',
        },
        
        description: {
            label: 'Description',
            placeholder: 'Describe the income or sales revenue in detail...',
            type: 'textarea',
            description: 'Detailed description of the income or sales transaction',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
        
        requester_id: {
            label: 'Requester',
            placeholder: 'Select requester',
            type: 'select',
            hidden: true,
            options: 'users',
            description: 'Employee recording this income',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
            nameField: 'requester_name',
        },
        
        requester_name: {
            label: 'Requester Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who recorded this income',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
        },
        
        department_id: {
            label: 'Department',
            placeholder: 'Select department',
            type: 'select',
            required: true,
            options: 'departments',
            description: 'Department responsible for this income',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'departments',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
            nameField: 'department_name',
        },
        
        department_name: {
            label: 'Department Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Department name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        
        location_id: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            hidden: true,
            options: 'locations',
            description: 'Location where income was generated',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
            nameField: 'location_name',
        },
        
        location_name: {
            label: 'Location Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Location name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        
        credit_amount: {
            label: 'Total Amount',
            placeholder: '0.00',
            hidden: true,
            type: 'number',
            description: 'Total income amount',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: function(value) {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Amount cannot be negative',
            },
        },
        
        currency_id: {
            label: 'Currency',
            placeholder: 'USD',
            type: 'select',
            options: 'currencies',
            default: 'USD',
            description: 'Currency for this income',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        
        currency_name: {
            label: 'Currency',
            placeholder: 'NGR',
            hidden: false,
            type: 'select',
            options: 'currencies',
            default: 'NGR',
            description: 'Currency for this income',
            showInTable: false,
            showInForm: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        
        approver_id: {
            label: 'Approver',
            placeholder: 'Select approver',
            hidden: true,
            type: 'select',
            options: 'users',
            description: 'Person who approved this income',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
            nameField: 'approver_name',
        },
        
        approver_name: {
            label: 'Approver Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Approver full name',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        
        approve_date: {
            label: 'Approval Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            description: 'Date when the income was approved',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        
        approval_workflow_id: {
            label: 'Approval Workflow',
            placeholder: 'Select workflow',
            hidden: true,
            type: 'select',
            options: 'approval_workflows',
            description: 'Approval workflow to follow',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'approval_workflows',
            analyzable: false,
            nameField: 'approval_workflow_name',
        },
        
        approval_workflow_name: {
            label: 'Workflow Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Approval workflow name',
            showInTable: true,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        
        current_approval_level: {
            label: 'Current Approval Level',
            type: 'number',
            disabled: true,
            hidden: true,
            description: 'Current step in approval workflow',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'approval',
        },
        
        created_at: {
            label: 'Start Date',
            type: 'date',
            description: 'Start date of this income period',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        
        expected_delivery_date: {
            label: 'End Date',
            type: 'date',
            description: 'End date of this income period',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        
        created_by_id: {
            label: 'Created By',
            type: 'select',
            options: 'users',
            hidden: true,
            disabled: true,
            description: 'User who created this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
            nameField: 'created_by_name',
        },
        
        created_by_name: {
            label: 'Created By',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Creator full name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        
        notes: {
            label: 'Notes',
            placeholder: 'Additional notes...',
            type: 'textarea',
            description: 'Additional notes or comments',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
       
        updated_at: {
            label: 'Updated Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        
        updated_by_id: {
            label: 'Updated By',
            type: 'select',
            options: 'users',
            disabled: true,
            hidden: true,
            description: 'User who last updated this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
            nameField: 'updated_by_name',
        },
        
        updated_by_name: {
            label: 'Updated By',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Updater full name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
        },
    },
};

export default incomes;