// src/config/incomeitems.js

const incomeitems = {
    frontendRoutes: ['/procurement/incomes/items'],
    description: 'Income this are the list of income generation items or sales items',
    form: 'IncomeItemForm',
    tableName: 'incomeitems',
    displayName: 'Income Items',
    icon: 'ShoppingBag',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { approval_status: 0 },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'category_id',
        defaultMetric: 'total_price',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'total_price', 'avg_price', 'quantity_sum', 'pending_count', 'approved_count'],
        availableDimensions: ['category_id', 'approval_status', 'resolved', 'created_at'],
    },
    fields: {
        id: {
            label: 'Item ID',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Auto-generated item identifier',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        income_id: {
            label: 'Income ID',
            type: 'number',
            hidden: true,
            disabled: true,
            description: 'Reference to parent income',
            showInTable: false,
            filterable: true,
            filterType: 'number',
            analyzable: false,
        },
        income_number: {
            label: 'Income Number',
            type: 'text',
             hidden: true,
            disabled: true,
            description: 'Parent income number',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        sku_id: {
            label: 'PO ID',
            type: 'number',
            hidden: true,
            description: 'Reference to purchase order',
            showInTable: false,
            filterable: true,
            filterType: 'number',
            analyzable: false,
        },
        po_number: {
            label: 'PO Number',
            type: 'text',
             hidden: true,
            disabled: true,
            description: 'Purchase order number',
            showInTable: true,
            tableWidth: '130px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        category_id: {
            label: 'Category',
            placeholder: 'Select category',
            type: 'select',
            required: true,
            options: 'categories',
            description: 'Item category',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'categories',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'category',
            nameField: 'category_name',
        },
        category_name: {
            label: 'Category',
             hidden: true,
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Category name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'category',
        },
        item_id: {
           label: 'item',
            placeholder: 'Select Item',
            type: 'select',
            required: true,
            options: 'items',
            description: 'Items',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'items',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'item',
            nameField: 'item_name',
        },
        item_name: {
            label: 'Item Name',
             hidden: true,
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Item name from master list',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'item',
        },
        quantity: {
            label: 'Quantity',
            placeholder: '0',
            type: 'number',
            description: 'Quantity (leave blank for services)',
            showInTable: true,
            showInForm: true,
            tableWidth: '100px',
            tableAlign: 'right',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'quantity',
            validation: {
                minValue: 0,
                message: 'Quantity cannot be negative',
            },
        },
        unit_price: {
            label: 'Unit Price',
            placeholder: '0.00',
            type: 'number',
            required: true,
            description: 'Price per unit',
            showInTable: true,
            showInForm: true,
            tableWidth: '130px',
            tableAlign: 'right',
            tableFormat: function(value) {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Price cannot be negative',
            },
        },
        credit_price: {
            label: 'Total Price',
            type: 'number',
            disabled: true,
            description: 'Quantity × Unit Price',
            showInTable: true,
            showInForm: false,
            tableWidth: '130px',
            tableAlign: 'right',
            tableFormat: function(value) {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
        },
        delivery_required_by: {
            label: 'Sales Date',
            type: 'date',
            description: 'Date item was sold',
            showInTable: true,
            showInForm: true,
            tableWidth: '140px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        special_instructions: {
            label: 'Special Information',
            placeholder: 'Any special requirements...',
            type: 'textarea',
            description: 'Special handling or delivery instructions',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
        resolved: {
            label: 'Resolved',
             hidden: true,
            type: 'select',
            options: 'yes_no',
            default: false,
            description: 'Whether the item has been resolved',
            showInTable: true,
            showInForm: true,
            tableWidth: '100px',
            tableFormat: function(value) {
                return value ? '✅' : '❌';
            },
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        resolved_date: {
            label: 'Resolved Date',
            type: 'datetime',
             hidden: true,
            disabled: true,
            description: 'When the item was resolved',
            showInTable: true,
            showInForm: false,
            tableWidth: '160px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        resolved_by_id: {
            label: 'Resolved By',
            type: 'select',
            hidden: true,
            options: 'users',
            description: 'User who resolved this item',
            showInTable: false,
            showInForm: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'resolver',
            nameField: 'resolved_by_name',
        },
        resolved_by_name: {
            label: 'Resolved By',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Resolver full name',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'resolver',
        },
        approved_by_id: {
            label: 'Approved By',
            type: 'select',
            hidden: true,
            options: 'users',
            description: 'User who approved this item',
            showInTable: false,
            showInForm: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
            nameField: 'approved_by_name',
        },
        approved_by_name: {
            label: 'Approved By',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Approver full name',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        approved_date: {
            label: 'Approved Date',
            type: 'datetime',
            disabled: true,
             hidden: true,
            description: 'When the item was approved',
            showInTable: true,
            showInForm: false,
            tableWidth: '160px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        approval_status: {
            label: 'Approval Status',
            placeholder: '0',
             hidden: true,
            type: 'select',
            options: 'approval_status',
            default: 0,
            description: '0: Pending, 1: Approved, 2: Rejected',
            showInTable: true,
            showInForm: true,
            tableWidth: '140px',
            tableFormat: function(value) {
                const statuses = {
                    0: '⏳ Pending',
                    1: '✅ Approved',
                    2: '❌ Rejected',
                };
                return statuses[value] || 'Unknown';
            },
            filterable: true,
            filterType: 'select',
            filterOptions: 'approval_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
             hidden: true,
            showInTable: true,
            showInForm: false,
            tableWidth: '160px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        created_by_id: {
            label: 'Created By',
            type: 'select',
            options: 'users',
             hidden: true,
            hidden: true,
            disabled: true,
            description: 'User who created this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
            nameField: 'created_by_name',
        },
        created_by_name: {
            label: 'Created By',
            type: 'text',
             hidden: true,
            hidden: false,
            disabled: true,
            description: 'Creator full name',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        updated_at: {
            label: 'Updated Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        updated_by_id: {
            label: 'Updated By',
            type: 'select',
             hidden: true,
            options: 'users',
            disabled: true,
            hidden: true,
            description: 'User who last updated this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
            nameField: 'updated_by_name',
        },
        updated_by_name: {
            label: 'Updated By',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Updater full name',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
        },
    },
};

export default incomeitems;