const invoices = {
    frontendRoutes: ['/finance/payable'],
    description: 'Vendor invoices for goods/services',
    form: 'InvoiceForm',
    tableName: 'invoices',
    displayName: 'Invoices',
    icon: 'ReceiptText',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: ['received', 'verified', 'approved'] },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'vendor_id',
        defaultMetric: 'total_amount',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'total_amount', 'avg_amount', 'tax_total', 'discount_total'],
        availableDimensions: ['vendor_id', 'status', 'created_at', 'payment_terms'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        invoice_number: {
            label: 'Invoice Number',
            placeholder: 'INV-001',
            type: 'text',
            required: true,
            description: 'Vendor invoice number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        po_id: {
            label: 'Purchase Order',
            placeholder: 'Select PO',
            type: 'select',
            options: 'purchase_orders',
            description: 'Associated purchase order',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'purchase_orders',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'po',
        },
        vendor_id: {
            label: 'Vendor',
            placeholder: 'Select vendor',
            type: 'select',
            required: true,
            options: 'vendors',
            description: 'Vendor issuing the invoice',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'vendors',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
        },
        invoice_date: {
            label: 'Invoice Date',
            type: 'date',
            required: true,
            description: 'Date of the invoice',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        due_date: {
            label: 'Due Date',
            type: 'date',
            required: true,
            description: 'Payment due date',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        subtotal: {
            label: 'Subtotal',
            placeholder: '0.00',
            type: 'number',
            required: true,
            description: 'Invoice subtotal before tax',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Subtotal cannot be negative',
            },
        },
        tax_amount: {
            label: 'Tax Amount',
            placeholder: '0.00',
            type: 'number',
            description: 'Tax amount on the invoice',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Tax amount cannot be negative',
            },
        },
        discount_amount: {
            label: 'Discount Amount',
            placeholder: '0.00',
            type: 'number',
            description: 'Any discount applied',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Discount cannot be negative',
            },
        },
        total_amount: {
            label: 'Total Amount',
            placeholder: '0.00',
            type: 'number',
            required: true,
            disabled: true,
            description: 'Total invoice amount (auto-calculated)',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Total cannot be negative',
            },
        },
        currency: {
            label: 'Currency',
            placeholder: 'USD',
            type: 'select',
            options: 'currencies',
            default: 'USD',
            description: 'Invoice currency',
            showInTable: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        grn_id: {
            label: 'GRN',
            placeholder: 'Select GRN',
            type: 'select',
            options: 'grns',
            description: 'Associated goods received note',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'grns',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'grn',
        },
        status: {
            label: 'Status',
            placeholder: 'received',
            type: 'select',
            options: 'invoice_status',
            disabled: true,
            description: 'Current invoice status',
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                const statuses = {
                    received: 'Received',
                    verified: 'Verified',
                    approved: 'Approved',
                    paid: 'Paid',
                    overdue: 'Overdue',
                    cancelled: 'Cancelled',
                    disputed: 'Disputed',
                };
                return statuses[value] || value;
            },
            filterable: true,
            filterType: 'select',
            filterOptions: 'invoice_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        payment_terms: {
            label: 'Payment Terms',
            placeholder: 'Select terms',
            type: 'select',
            options: 'payment_terms',
            description: 'Payment terms for this invoice',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'payment_terms',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'payment_terms',
        },
        notes: {
            label: 'Notes',
            placeholder: 'Additional notes',
            type: 'textarea',
            description: 'Additional notes about the invoice',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        created_by: {
            label: 'Created By',
            placeholder: 'Select user',
            type: 'select',
            required: true,
            options: 'users',
            description: 'User who created the invoice record',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        approved_by: {
            label: 'Approved By',
            placeholder: 'Select approver',
            type: 'select',
            options: 'users',
            description: 'User who approved the invoice',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        approved_at: {
            label: 'Approved Date',
            type: 'datetime',
            disabled: true,
            description: 'Date the invoice was approved',
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default invoices;