const payments = {
    frontendRoutes: ['/finance/payments'],
    description: 'Payment records against invoices',
    form: 'PaymentForm',
    tableName: 'payments',
    displayName: 'Payments',
    icon: 'CreditCard',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: ['initiated', 'processing', 'completed'] },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'vendor_id',
        defaultMetric: 'amount_paid',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'amount_paid', 'avg_payment', 'total_by_method'],
        availableDimensions: ['vendor_id', 'payment_method', 'status', 'created_at'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        payment_number: {
            label: 'Payment Number',
            placeholder: 'PAY-2026-001',
            type: 'text',
            disabled: true,
            description: 'Auto-generated payment number',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        invoice_id: {
            label: 'Invoice',
            placeholder: 'Select invoice',
            type: 'select',
            required: true,
            options: 'invoices',
            description: 'Invoice being paid',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'invoices',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'invoice',
        },
        vendor_id: {
            label: 'Vendor',
            placeholder: 'Select vendor',
            type: 'select',
            required: true,
            options: 'vendors',
            description: 'Vendor receiving payment',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'vendors',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
        },
        payment_date: {
            label: 'Payment Date',
            type: 'date',
            required: true,
            description: 'Date of payment',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        amount_paid: {
            label: 'Amount Paid',
            placeholder: '0.00',
            type: 'number',
            required: true,
            description: 'Amount being paid',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Amount cannot be negative',
            },
        },
        currency: {
            label: 'Currency',
            placeholder: 'USD',
            type: 'select',
            options: 'currencies',
            default: 'USD',
            description: 'Payment currency',
            showInTable: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'currencies',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        payment_method: {
            label: 'Payment Method',
            placeholder: 'Select method',
            type: 'select',
            required: true,
            options: 'payment_methods',
            description: 'Method of payment',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'payment_methods',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'method',
        },
        reference_number: {
            label: 'Reference Number',
            placeholder: 'REF-001',
            type: 'text',
            description: 'Payment reference or transaction ID',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        bank_account: {
            label: 'Bank Account',
            placeholder: 'Account number',
            type: 'text',
            description: 'Bank account used for payment',
            showInTable: false,
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        status: {
            label: 'Status',
            placeholder: 'initiated',
            type: 'select',
            options: 'payment_status',
            disabled: true,
            description: 'Current payment status',
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                const statuses = {
                    initiated: 'Initiated',
                    processing: 'Processing',
                    completed: 'Completed',
                    failed: 'Failed',
                    reversed: 'Reversed',
                    pending_approval: 'Pending Approval',
                };
                return statuses[value] || value;
            },
            filterable: true,
            filterType: 'select',
            filterOptions: 'payment_status',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        notes: {
            label: 'Notes',
            placeholder: 'Additional notes',
            type: 'textarea',
            description: 'Additional notes about the payment',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        created_by: {
            label: 'Created By',
            placeholder: 'Select user',
            type: 'select',
            required: true,
            options: 'users',
            description: 'User who created the payment',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        approved_by: {
            label: 'Approved By',
            placeholder: 'Select approver',
            type: 'select',
            options: 'users',
            description: 'User who approved the payment',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        approved_at: {
            label: 'Approved Date',
            type: 'datetime',
            disabled: true,
            description: 'Date the payment was approved',
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};
export default payments;