const skus = {
    frontendRoutes: ['/inventory/stock', '/settings/taxes'],
    description: 'Stock Keeping Units - inventory items',
    form: 'SKUForm',
    tableName: 'skus',
    displayName: 'Stock Keeping Units',
    icon: 'Boxes',
    defaultSort: { field: 'item_name', direction: 'ASC' },
    defaultFilters: { is_tracked: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'category_id',
        defaultMetric: 'current_stock',
        chartTypes: ['bar', 'pie', 'table', 'scatter'],
        availableMetrics: ['count', 'current_stock', 'unit_cost', 'total_value'],
        availableDimensions: ['category_id', 'is_tracked', 'is_consumable', 'location_id'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        sku_code: {
            label: 'SKU Code',
            placeholder: 'SKU-001',
            type: 'text',
            required: true,
            description: 'Unique stock keeping unit identifier',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        item_name: {
            label: 'Item Name',
            placeholder: 'HP Laptop',
            type: 'text',
            required: true,
            description: 'Name of the inventory item',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'item',
        },
        description: {
            label: 'Description',
            placeholder: 'Detailed item description',
            type: 'textarea',
            description: 'Detailed description of the item',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        category_id: {
            label: 'Category',
            placeholder: 'Select category',
            type: 'select',
            required: true,
            options: 'item_categories',
            description: 'Category this item belongs to',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'item_categories',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'category',
        },
        unit_of_measure: {
            label: 'Unit of Measure',
            placeholder: 'Select unit',
            type: 'select',
            options: 'units',
            description: 'Unit of measurement (each, kg, etc.)',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'units',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'unit',
        },
        min_stock_level: {
            label: 'Min Stock Level',
            placeholder: '10',
            type: 'number',
            description: 'Minimum stock level before reorder',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'stock',
            validation: {
                minValue: 0,
                message: 'Stock level cannot be negative',
            },
        },
        max_stock_level: {
            label: 'Max Stock Level',
            placeholder: '100',
            type: 'number',
            description: 'Maximum stock level allowed',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'stock',
            validation: {
                minValue: 0,
                message: 'Stock level cannot be negative',
            },
        },
        current_stock: {
            label: 'Current Stock',
            placeholder: '0',
            type: 'number',
            disabled: true,
            description: 'Current quantity in stock',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'stock',
        },
        reorder_point: {
            label: 'Reorder Point',
            placeholder: '20',
            type: 'number',
            description: 'Stock level that triggers reorder',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'stock',
            validation: {
                minValue: 0,
                message: 'Reorder point cannot be negative',
            },
        },
        unit_cost: {
            label: 'Unit Cost',
            placeholder: '0.00',
            type: 'number',
            required: true,
            description: 'Cost per unit of the item',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Unit cost cannot be negative',
            },
        },
        selling_price: {
            label: 'Selling Price',
            placeholder: '0.00',
            type: 'number',
            description: 'Selling price per unit',
            showInTable: true,
            tableWidth: '150px',
            tableAlign: 'right',
            tableFormat: (value) => {
                if (!value) return '$0.00';
                return new Intl.NumberFormat('en-US', {
                    style: 'currency',
                    currency: 'USD',
                }).format(value);
            },
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Selling price cannot be negative',
            },
        },
        is_tracked: {
            label: 'Track Stock',
            type: 'toggle',
            default: true,
            description: 'Whether stock quantity is tracked',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'tracking',
        },
        is_consumable: {
            label: 'Consumable',
            type: 'toggle',
            default: true,
            description: 'Whether item is consumable or reusable',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'type',
        },
        tax_rate: {
            label: 'Tax Rate',
            placeholder: 'Select tax rate',
            type: 'select',
            options: 'tax_rates',
            description: 'Tax rate applied to this item',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'tax_rates',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'tax',
        },
        location_id: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            options: 'locations',
            description: 'Location where stock is stored',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        supplier_id: {
            label: 'Supplier',
            placeholder: 'Select supplier',
            type: 'select',
            options: 'vendors',
            description: 'Primary supplier for this item',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'vendors',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'supplier',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default skus;