// src/config/purchaseStocks.js

const stocks = {
    frontendRoutes: ['/procurement/stocks'],
    description: 'Manage stock requisition orders to fulfill approved requisitions from available inventory. This module handles the picking, packing, and issuance of items from the store/warehouse. Items not available in stock are automatically flagged for purchase order processing.',
    form: 'StockForm',
    tableName: 'stocks',
    displayName: 'Stock Requisition & Issuance',
    icon: 'ShoppingCart',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: { status: 'pending_approval' },
    
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'department_id',
        defaultMetric: 'total_amount',
        chartTypes: ['bar', 'pie', 'table', 'line', 'scatter'],
        availableMetrics: ['count', 'total_amount', 'avg_amount', 'pending_count', 'approved_count'],
        availableDimensions: ['department_id', 'stock_type', 'status', 'priority', 'created_at'],
    },
    
    fields: {
        id: {
            label: 'Stock Reference',
            type: 'text',
            hidden: true,
            disabled: true,
            description: 'Auto-generated unique reference number for this stock requisition order',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        
        title: {
            label: 'Requisition Title',
            placeholder: 'e.g., Office Supplies Stock Release, IT Equipment Issuance',
            type: 'text',
            required: true,
            description: 'A clear title identifying this stock requisition and its purpose',
            showInTable: true,
            showInForm: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'title',
        },
        
        description: {
            label: 'Requisition Description',
            placeholder: 'Provide details about the stock being requested, including purpose, urgency, and any special handling requirements...',
            type: 'textarea',
            description: 'Detailed description of the stock requisition, including purpose and special instructions',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
      
        requester_id: {
            label: 'Requester',
            placeholder: 'Select requester',
            type: 'select',
            hidden: true,
            options: 'users',
            description: 'The staff member requesting these items from stock',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
            nameField: 'requester_name',
        },
        
        requester_name: {
            label: 'Requester Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person requesting stock items',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'requester',
        },
        
        department_id: {
            label: 'Department',
            placeholder: 'Select department',
            type: 'select',
            required: true,
            options: 'departments',
            description: 'Department requesting these stock items',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'departments',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
            nameField: 'department_name',
        },
        
        department_name: {
            label: 'Department Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Department name',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        
        location_id: {
            label: 'Store/Warehouse Location',
            placeholder: 'Select store location',
            type: 'select',
            hidden: true,
            options: 'locations',
            description: 'Store or warehouse location where items will be picked from',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
            nameField: 'location_name',
        },
        
        location_name: {
            label: 'Store Location Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Location name of the store/warehouse',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        
        total_amount: {
            label: 'Total Stock Value',
            placeholder: '0.00',
            hidden: true,
            type: 'number',
            description: 'Total estimated value of all stock items being requested',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableAlign: 'right',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'sum',
            analysisGroup: 'financial',
            validation: {
                minValue: 0,
                message: 'Amount cannot be negative',
            },
        },
        
        approver_id: {
            label: 'Approver',
            placeholder: 'Select approver',
            hidden: true,
            type: 'select',
            options: 'users',
            description: 'The person who approved or will approve this stock requisition',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
            nameField: 'approver_name',
        },
        
        approver_name: {
            label: 'Approver Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who approved this stock requisition',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'approver',
        },
        
        approve_date: {
            label: 'Approval Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            description: 'Date and time when this stock requisition was approved',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        
        approval_workflow_id: {
            label: 'Approval Workflow',
            placeholder: 'Select approval workflow',
            hidden: true,
            type: 'select',
            options: 'approval_workflows',
            description: 'The approval workflow assigned to this stock requisition',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'approval_workflows',
            analyzable: false,
            nameField: 'approval_workflow_name',
        },
        
        approval_workflow_name: {
            label: 'Workflow Name',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Approval workflow name',
            showInTable: true,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        
        current_approval_level: {
            label: 'Current Approval Level',
            type: 'number',
            disabled: true,
            hidden: true,
            description: 'Current step in the approval workflow',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'avg',
            analysisGroup: 'approval',
        },
        
        expected_delivery_date: {
            label: 'Expected Issuance Date',
            type: 'date',
            description: 'Expected date when items will be issued/picked from stock',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            tableFormat: function(value) {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'timeline',
        },
        
        created_at: {
            label: 'Created Date',
            type: 'date',
            description: 'Date when this stock requisition was created',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        
        created_by_id: {
            label: 'Created By',
            type: 'select',
            options: 'users',
            hidden: true,
            disabled: true,
            description: 'User who created this stock requisition record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
            nameField: 'created_by_name',
        },
        
        created_by_name: {
            label: 'Created By',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who created this record',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'creator',
        },
        
        notes: {
            label: 'Notes',
            placeholder: 'Add any special instructions or additional information...',
            type: 'textarea',
            description: 'Additional notes, special instructions, or comments about this stock requisition',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
       
        updated_at: {
            label: 'Updated Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        
        updated_by_id: {
            label: 'Updated By',
            type: 'select',
            options: 'users',
            disabled: true,
            hidden: true,
            description: 'User who last updated this record',
            showInTable: false,
            showInForm: true,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
            nameField: 'updated_by_name',
        },
        
        updated_by_name: {
            label: 'Updated By',
            type: 'text',
            hidden: false,
            disabled: true,
            description: 'Full name of the person who last updated this record',
            showInTable: true,
            showInForm: false,
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'updater',
        },
    },
};

export default stocks;