// src/config/accounts/accounts.ts
const accounts = {
    frontendRoutes: ['/teams/accounts', '/finance/budgets'],
    description: 'All accounts available for transaction',
    form: 'AccountForm',
    tableName: 'commons',
    groupid:7,
    grp:7,
    displayName: 'Accounts & Banks',
    icon: 'Money',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'budget_allocated',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'budget_allocated', 'budget_used', 'budget_remaining'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Account Code',
            placeholder: 'FIN-001',
            type: 'text',
            required: true,
            description: 'Unique account identifier code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Account/ Bank Name',
            placeholder: 'Finance Account',
            type: 'text',
            required: true,
            description: 'Full account name',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'account',
        },
         comment1: {
            label: 'Account Description',
            placeholder: '...',
            type: 'textarea',
            required: true,
            description: 'Explain the account, its purpose etc',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
            analysisType: 'group',
            analysisGroup: 'account',
        },
        comment2: {
            label: 'Address',
            placeholder: '...',
            type: 'textarea',
            required: false,
            description: 'Give full details of contact details',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'account',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether the account is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};
export default accounts;