// src/config/approvalactions/approvalactions.ts
const approvalactions = {
    frontendRoutes: ['/settings/approval-actions', '/workflows/actions'],
    description: 'Actions that can be taken during approval process',
    form: 'ApprovalActionForm',
    tableName: 'commons',
    groupid: 12,
    grp: 12,
    displayName: 'Approval Actions',
    icon: 'ThumbsUp',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 12, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'bool_1',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['bool_1', 'bool_2', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Action Code',
            placeholder: 'APPROVE',
            type: 'text',
            required: true,
            description: 'Unique action code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Action Name',
            placeholder: 'Approve',
            type: 'text',
            required: true,
            description: 'Display name for the action',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'action',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'What this action does',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        text_1: {
            label: 'Requires Comment',
            type: 'toggle',
            default: true,
            description: 'Does this action require comments?',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'requirements',
        },
        text_2: {
            label: 'Requires Password',
            type: 'toggle',
            default: false,
            description: 'Does this action require password confirmation?',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'requirements',
        },
        item_id1: {
            label: 'Affects Status',
            placeholder: 'Select status',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 11 },
            description: 'Status this action sets',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_11',
            analyzable: false,
        },
        item_name1: {
            label: 'Status Name',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
            analyzable: false,
            // This will be populated via JOIN with commons
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this action is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default approvalactions;