// src/config/purchase_requisitions/audittrail.ts
const audittrail = {
    frontendRoutes: ['/audit/logs', '/settings/audit'],
    description: 'Complete audit trail of all system actions',
    form: 'AuditTrailForm',
    tableName: 'audittrail',
    displayName: 'Audit Trail',
    icon: 'Shield',
    defaultSort: { field: 'created_at', direction: 'DESC' },
    defaultFilters: {},
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'action_type',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['action_type', 'module', 'user_id', 'role_id'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
        },
        user_id: {
            label: 'User',
            type: 'select',
            options: 'users',
            required: true,
            description: 'User who performed the action',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
        },
        user_name: {
            label: 'User Name',
            type: 'text',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
        },
        user_email: {
            label: 'User Email',
            type: 'text',
            disabled: true,
            showInTable: false,
        },
        role_name: {
            label: 'Role',
            type: 'text',
            disabled: true,
            showInTable: true,
            tableWidth: '120px',
            filterable: false,
        },
        action_type: {
            label: 'Action Type',
            placeholder: 'Select action',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 12 },
            required: true,
            description: 'Type of action performed',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_12',
        },
        action_name: {
            label: 'Action',
            type: 'text',
            disabled: true,
            showInTable: true,
            tableWidth: '120px',
            filterable: false,
        },
        module: {
            label: 'Module',
            type: 'text',
            required: true,
            description: 'Module where action occurred',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
        },
        table_name: {
            label: 'Table',
            type: 'text',
            required: true,
            description: 'Database table affected',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
        },
        record_id: {
            label: 'Record ID',
            type: 'number',
            description: 'ID of the record affected',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        record_identifier: {
            label: 'Record Identifier',
            type: 'text',
            description: 'Human-readable record identifier',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
        },
        status_from: {
            label: 'Previous Status',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 11 },
            description: 'Previous status before action',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_11',
        },
        status_to: {
            label: 'New Status',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 11 },
            description: 'New status after action',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_11',
        },
        field_name: {
            label: 'Field Name',
            type: 'text',
            description: 'Specific field that changed',
            showInTable: false,
            filterable: true,
            filterType: 'text',
        },
        old_value: {
            label: 'Old Value',
            type: 'textarea',
            description: 'Previous value',
            showInTable: false,
        },
        new_value: {
            label: 'New Value',
            type: 'textarea',
            description: 'New value',
            showInTable: false,
        },
        comments: {
            label: 'Comments',
            type: 'textarea',
            description: 'Additional comments',
            showInTable: false,
        },
        ip_address: {
            label: 'IP Address',
            type: 'text',
            description: 'User IP address',
            showInTable: true,
            tableWidth: '130px',
            filterable: true,
            filterType: 'text',
        },
        session_id: {
            label: 'Session ID',
            type: 'text',
            description: 'Session identifier',
            showInTable: false,
            filterable: true,
            filterType: 'text',
        },
        metadata: {
            label: 'Metadata',
            type: 'json',
            description: 'Additional structured data',
            showInTable: false,
        },
        created_at: {
            label: 'Timestamp',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
        },
    },
};

export default audittrail;