// src/config/currencys/currencys.ts
const currencys = {
    frontendRoutes: ['/teams/currencys', '/finance/budgets'],
    description: 'Various currencies the company would be transacting with',
    form: 'CurrencyForm',
    tableName: 'commons',
    groupid:6,
    grp:6,
    displayName: 'Currencies',
    icon: 'Money',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'budget_allocated',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'budget_allocated', 'budget_used', 'budget_remaining'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Currency Code',
            placeholder: 'FIN-001',
            type: 'text',
            required: true,
            description: 'Unique currency identifier code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Currency Name',
            placeholder: 'Finance Currency',
            type: 'text',
            required: true,
            description: 'Full currency name',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
         comment1: {
            label: 'Currency Description',
            placeholder: '...',
            type: 'textarea',
            required: true,
            description: 'Explain the currency, its purpose etc',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'currency',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether the currency is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};
export default currencys;