// src/config/departments/departments.ts
const departments = {
    frontendRoutes: ['/teams/departments', '/finance/budgets'],
    description: 'Organizational departments with budgets',
    form: 'DepartmentForm',
    tableName: 'departments',
    groupid:2,
    grp:2,
    displayName: 'Departments',
    icon: 'Building2',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'budget_allocated',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'budget_allocated', 'budget_used', 'budget_remaining'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Department Code',
            placeholder: 'FIN-001',
            type: 'text',
            required: true,
            description: 'Unique department identifier code',
            showInTable: true,
            tableWidth: '60px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Department Name',
            placeholder: 'Finance Department',
            type: 'text',
            required: true,
            description: 'Full department name',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
         comment1: {
            label: 'Department Description',
            placeholder: '...',
            type: 'textarea',
            required: true,
            description: 'Explain the department, its purpose etc',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        user_id1: {
            label: 'Department Head',
            placeholder: 'Select department head',
            type: 'select',
            options: 'users',
            description: 'User who heads this department',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: false,
        },
        item_id1: {
            label: 'Location',
            placeholder: 'Select location',
            type: 'select',
            options: 'locations',
            description: 'Primary location of the department',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether the department is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};
export default departments;