// src/config/documenttypes/documenttypes.ts
const documenttypes = {
    frontendRoutes: ['/settings/document-types', '/workflows/document-types'],
    description: 'Document types used in the workflow system',
    form: 'DocumentTypeForm',
    tableName: 'commons',
    groupid: 10,
    grp: 10,
    displayName: 'Document Types',
    icon: 'FileText',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 10, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'is_active',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Document Code',
            placeholder: 'REQUISITION',
            type: 'text',
            required: true,
            description: 'Unique document type code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Document Name',
            placeholder: 'Requisition',
            type: 'text',
            required: true,
            description: 'Display name for the document type',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'document_type',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Detailed description of this document type',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        text_1: {
            label: 'Color Code',
            placeholder: '#4A90D9',
            type: 'color',
            description: 'Color for UI display',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => `<span style="color:${value}">●</span> ${value}`,
            filterable: false,
            analyzable: false,
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this document type is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default documenttypes;