// src/config/documentcategories/documentcategories.ts
const documentcategories = {
    frontendRoutes: ['/settings/document-categories', '/documents/categories'],
    description: 'Categories for document classification',
    form: 'DocumentCategoryForm',
    tableName: 'commons',
    groupid: 19,
    grp: 19,
    displayName: 'Document Categories',
    icon: 'Folder',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 19, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'is_active',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Category Code',
            placeholder: 'OFFICE',
            type: 'text',
            required: true,
            description: 'Unique category code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Category Name',
            placeholder: 'Office Supplies',
            type: 'text',
            required: true,
            description: 'Display name for the category',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'category',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Description of this category',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this category is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default documentcategories;