// src/config/documentstatus/documentstatus.ts
const documentstatus = {
    frontendRoutes: ['/settings/document-status', '/documents/status'],
    description: 'Status values for documents (requisitions, POs, etc.)',
    form: 'DocumentstatusForm',
    tableName: 'commons',
    groupid: 13,
    grp: 13,
    displayName: 'Document Status',
    icon: 'ClipboardList',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 13, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'item_id1',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['item_id1', 'bool_1', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Status Code',
            placeholder: 'APPROVED',
            type: 'text',
            required: true,
            description: 'Unique status code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Status Name',
            placeholder: 'Approved',
            type: 'text',
            required: true,
            description: 'Display name for the status',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'What this status means',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        item_id1: {
            label: 'Document Type',
            placeholder: 'Select document type',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 10 },
            description: 'Which document type this status applies to',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_10',
            analyzable: false,
        },
        item_name1: {
            label: 'Document Type',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
            analyzable: false,
            // This will be populated via JOIN with commons
        },
        bool_1: {
            label: 'Is Terminal',
            type: 'toggle',
            default: false,
            description: 'Is this a final/end state?',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status_type',
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this status is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default documentstatus;