// src/config/expenses/expenses.ts

const expenses = {
    frontendRoutes: ['/teams/expenses', '/finance/budgets'],
    description: 'Manage expense and income categories used across the organization for financial planning, budgeting, and procurement. Each category can be customized with specific items that define whether they represent expenses, income, or both, and whether they are goods or services.',
    form: 'ExpenseForm',
    tableName: 'commons',
    groupid: 5,
    grp: 5,
    displayName: 'Expense & Income Categories',
    icon: 'Building2',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'budget_allocated',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'budget_allocated', 'budget_used', 'budget_remaining'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'Group',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Category Code',
            placeholder: 'e.g., EXP-001, INC-001, OPS-002',
            type: 'text',
            required: true,
            description: 'Unique identifier code for this expense or income category',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Category Name',
            placeholder: 'e.g., Office Supplies, IT Equipment, Service Revenue',
            type: 'text',
            required: true,
            description: 'Full name of the expense or income category',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'expense',
        },
        comment1: {
            label: 'Category Description',
            placeholder: 'Describe the purpose and scope of this category...',
            type: 'textarea',
            required: true,
            description: 'Detailed description explaining what this category covers and its purpose',
            showInTable: true,
            tableWidth: '250px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'expense',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this category is currently active and available for use',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default expenses;