// src/config/items/expenseitems.ts

const expenseitems = {
    frontendRoutes: ['/teams/expenses/items', '/finance/budgets'],
    description: 'Organizational expense items',
    form: 'itemForm',
    tableName: 'commons',
    groupid: 51 ,
    grp: 51,
    displayName: 'Expense Items',
    icon: 'Building2',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        parent_id: {
            label: 'Parent ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'Group',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Item Code',
            placeholder: 'EXP-001',
            type: 'text',
            required: true,
            description: 'Unique expense item identifier code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Item Name',
            placeholder: 'Enter expense item name',
            type: 'text',
            required: true,
            description: 'Full expense item name',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'item',
        },
        comment1: {
            label: 'Item Description',
            placeholder: 'Enter description...',
            type: 'textarea',
            required: false,
            description: 'Explain the expense item, its purpose, etc.',
            showInTable: true,
            tableWidth: '250px',
            filterable: false,
            filterType: 'text',
            analyzable: false,
        },
    text_1: {
            label: 'Unit of Measure',
            placeholder: 'Enter unit of measure...',
            type: 'textarea',
            required: false,
            description: 'Unit of measure for the expense item, e.g., pieces, liters, etc.',
            showInTable: true,
            tableWidth: '250px',
            filterable: false,
            filterType: 'text',
            analyzable: false,
        },
    id_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether the expense item is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅ Active' : '❌ Inactive',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '180px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        updated_at: {
            label: 'Last Updated',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '180px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default expenseitems;