// src/config/expenses/expenses.ts
const expenses = {
    frontendRoutes: ['/teams/expenses', '/finance/budgets'],
    description: 'Organizational expenses with budgets',
    form: 'ExpenseForm',
    tableName: 'commons',
    groupid:5,
    grp:5,
    displayName: 'Expenses',
    icon: 'Building2',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'budget_allocated',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'budget_allocated', 'budget_used', 'budget_remaining'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Expense Code',
            placeholder: 'FIN-001',
            type: 'text',
            required: true,
            description: 'Unique expense identifier code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Expense Name',
            placeholder: 'Finance Expense',
            type: 'text',
            required: true,
            description: 'Full expense name',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'expense',
        },
         comment1: {
            label: 'Expense Description',
            placeholder: '...',
            type: 'textarea',
            required: true,
            description: 'Explain the expense, its purpose etc',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'expense',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether the expense is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};
export default expenses;