// src/config/locations.ts

const locations = {
    frontendRoutes: ['/settings/branches'],
    description: 'Stores branch/office locations',
    form: 'LocationForm',
    tableName: 'locations',
    displayName: 'Locations',
    icon: 'MapPin',
    grp: 4,
    defaultSort: { field: 'location_name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'country',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'map'],
        availableMetrics: ['count', 'active_count'],
        availableDimensions: ['country', 'city', 'state', 'is_active'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Location Code',
            placeholder: 'LAG-001',
            type: 'text',
            required: true,
            description: 'Unique location identifier',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Location Name',
            placeholder: 'Lagos Office',
            type: 'text',
            required: true,
            description: 'Name of the location/Branch',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        comment1: {
            label: 'Address',
            placeholder: '123 Main Street',
            type: 'textarea',
            description: 'Street address of the location',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        text_1: {
            label: 'City',
            placeholder: 'Lagos',
            type: 'text',
            description: 'City where the location is situated',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'city',
        },
        text_2: {
            label: 'State',
            placeholder: 'Lagos State',
            type: 'text',
            description: 'State/Province of the location',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'state',
        },
        text_3: {
            label: 'Country',
            placeholder: 'Nigeria',
            type: 'text',
            description: 'Country of the location',
            showInTable: false,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'country',
        },
        // 🆕 New Fields
        text_4: {
            label: 'Postal/Zip Code',
            placeholder: '100001',
            type: 'text',
            description: 'Postal or zip code for the location',
            showInTable: false,
            tableWidth: '100px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        text_5: {
            label: 'Region',
            placeholder: 'South West',
            type: 'text',
            description: 'Region or district of the location',
            showInTable: false,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'region',
        },
        phone: {
            label: 'Phone Number',
            placeholder: '+234 800 000 0000',
            type: 'phone',
            required: false,
            description: 'Location contact phone number',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        email: {
            label: 'Email Address',
            placeholder: 'location@company.com',
            type: 'email',
            required: false,
            description: 'Location contact email address',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        // 🆕 About Location (comment2)
        comment2: {
            label: 'About Location',
            placeholder: 'Description of the location...',
            type: 'textarea',
            required: false,
            description: 'Additional information about the location (facilities, directions, etc.)',
            showInTable: false,
            filterable: false,
            analyzable: false,
            rows: 4,
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            hidden: true,
            default: true,
            description: 'Whether the location is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
    },
};

export default locations;