// src/config/notificationtypes/notificationtypes.ts
const notificationtypes = {
    frontendRoutes: ['/settings/notification-types', '/notifications/types'],
    description: 'Types of notifications in the system',
    form: 'NotificationTypeForm',
    tableName: 'commons',
    groupid: 16,
    grp: 16,
    displayName: 'Notification Types',
    icon: 'Bell',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 16, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'is_active',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Notification Code',
            placeholder: 'APPROVAL_REQUIRED',
            type: 'text',
            required: true,
            description: 'Unique notification code',
            showInTable: true,
            tableWidth: '160px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Notification Name',
            placeholder: 'Approval Required',
            type: 'text',
            required: true,
            description: 'Display name for the notification',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'notification_type',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Description of this notification type',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this notification type is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default notificationtypes;