// src/config/prioritylevels/prioritylevels.ts
const prioritylevels = {
    frontendRoutes: ['/settings/priority-levels', '/workflows/priorities'],
    description: 'Priority levels for workflow items',
    form: 'PriorityLevelForm',
    tableName: 'commons',
    groupid: 14,
    grp: 14,
    displayName: 'Priority Levels',
    icon: 'Flag',
    defaultSort: { field: 'item_id2', direction: 'ASC' },
    defaultFilters: { grp: 14, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'is_active',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'item_id2', 'item_id3'],
        availableDimensions: ['is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Priority Code',
            placeholder: 'HIGH',
            type: 'text',
            required: true,
            description: 'Unique priority code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Priority Name',
            placeholder: 'High',
            type: 'text',
            required: true,
            description: 'Display name for the priority',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'priority',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Description of this priority level',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        text_1: {
            label: 'Color Code',
            placeholder: '#4A90D9',
            type: 'color',
            description: 'Color for UI display',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => `<span style="color:${value}">●</span> ${value}`,
            filterable: false,
            analyzable: false,
        },
        item_id2: {
            label: 'Priority Weight',
            type: 'number',
            default: 0,
            description: 'Higher number = higher priority (e.g., 10=LOW, 50=CRITICAL)',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        item_id3: {
            label: 'Response Days',
            type: 'number',
            default: 3,
            description: 'Expected response time in days',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this priority is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default prioritylevels;