// src/config/rejectionreasons/rejectionreasons.ts
const rejectionreasons = {
    frontendRoutes: ['/settings/rejection-reasons', '/workflows/rejections'],
    description: 'Reasons for workflow rejection',
    form: 'RejectionReasonForm',
    tableName: 'commons',
    groupid: 18,
    grp: 18,
    displayName: 'Rejection Reasons',
    icon: 'XCircle',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 18, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'is_active',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Reason Code',
            placeholder: 'BUDGET',
            type: 'text',
            required: true,
            description: 'Unique reason code',
            showInTable: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Reason Name',
            placeholder: 'Budget Insufficient',
            type: 'text',
            required: true,
            description: 'Display name for the reason',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'reason',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Detailed description of this rejection reason',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this reason is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default rejectionreasons;