// src/config/roles/roles.ts
const roles = {
    frontendRoutes: ['/teams/roles', '/finance/budgets'],
    description: 'Organizational roles with budgets',
    form: 'RoleForm',
    tableName: 'datas',
    groupid:1,
    grp:1,
    displayName: 'Roles',
    icon: 'Building2',
    defaultSort: { field: 'name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'location_id',
        defaultMetric: 'budget_allocated',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'budget_allocated', 'budget_used', 'budget_remaining'],
        availableDimensions: ['location_id', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Role Code',
            placeholder: 'FIN-001',
            type: 'text',
            required: true,
            description: 'Unique role identifier code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Role Name',
            placeholder: 'Finance Role',
            type: 'text',
            required: true,
            description: 'Full role name',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'role',
        },
         comment1: {
            label: 'Role Description',
            placeholder: '...',
            type: 'textarea',
            required: true,
            description: 'Explain the role, its purpose etc',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'role',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether the role is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};
export default roles;