// src/config/tables/users.js

const users = {
    frontendRoutes: ['/teams/directory', '/advances/balances'],
    description: 'System users with authentication and permissions',
    form: 'UserForm',
    tableName: 'users',
    displayName: 'Users',
    icon: 'Users',
    defaultSort: { field: 'first_name', direction: 'ASC' },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'department_id',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table'],
        availableMetrics: ['count', 'active_count', 'inactive_count'],
        availableDimensions: ['department_id', 'is_active', 'created_at', 'employment_type'],
    },
    fields: {
        // ==================== IDENTITY ====================
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
        employee_id: {
            label: 'Employee ID',
            placeholder: 'EMP-001',
            type: 'text',
            required: true,
            description: 'Unique employee identifier',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        password: {
            label: 'Password',
            placeholder: '••••••••',
            type: 'password',
            required: true,
            description: 'User password',
            showInTable: false,
            showInForm: true,
            tableWidth: '120px',
            filterable: false,
            filterType: 'text',
            analyzable: false,
        },
        photo: {
            label: 'Profile Photo',
            type: 'file',
            hidden:true,
            accept: 'image/jpeg,image/png,image/gif,image/webp',
            description: 'User profile photo (JPEG, PNG, GIF, WEBP)',
            showInTable: true,
            showInForm: true,
            tableWidth: '80px',
            tableFormat: function(value) {
                if (!value) return '📷';
                return `<img src="${value}" alt="Profile" class="w-8 h-8 rounded-full object-cover" />`;
            },
            filterable: false,
            analyzable: false,
        },
        title: {
            label: 'Title',
            placeholder: 'Mr./Ms./Dr.',
            type: 'text',
            description: 'Personal title (Mr., Ms., Dr., etc.)',
            showInTable: false,
            showInForm: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        first_name: {
            label: 'First Name',
            placeholder: 'John',
            type: 'text',
            required: true,
            description: 'User first name',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        middle_name: {
            label: 'Middle Name',
            placeholder: 'Michael',
            type: 'text',
            description: 'User middle name (optional)',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        last_name: {
            label: 'Last Name',
            placeholder: 'Doe',
            type: 'text',
            required: true,
            description: 'User last name',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        phone: {
            label: 'Phone Number',
            placeholder: '+1 (555) 000-0000',
            type: 'phone',
            description: 'Primary contact phone number',
            showInTable: true,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        date_of_birth: {
            label: 'Date of Birth',
            type: 'date',
            description: 'Date of birth',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            tableFormat: function(value) {
                if (!value) return '';
                var date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'demographics',
        },

        // ==================== ADDRESS ====================
        address_line1: {
            label: 'Address Line 1',
            placeholder: '123 Main Street',
            type: 'text',
            description: 'Street address',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
        address_line2: {
            label: 'Address Line 2',
            placeholder: 'Apt 4B',
            type: 'text',
            description: 'Apartment, suite, unit, etc.',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },
        city: {
            label: 'City',
            placeholder: 'Lagos',
            type: 'text',
            description: 'City of residence',
            showInTable: false,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'demographics',
        },
        state: {
            label: 'State/Province',
            placeholder: 'Lagos State',
            type: 'text',
            description: 'State or province of residence',
            showInTable: false,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'demographics',
        },
        country: {
            label: 'Country',
            placeholder: 'Nigeria',
            type: 'text',
            description: 'Country of residence',
            showInTable: true,
            showInForm: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'demographics',
        },
        postal_code: {
            label: 'Postal Code',
            placeholder: '100001',
            type: 'text',
            description: 'Postal/ZIP code',
            showInTable: false,
            showInForm: true,
            filterable: false,
            analyzable: false,
        },

        // ==================== EMPLOYMENT ====================
        employment_type: {
            label: 'Employment Type',
            placeholder: 'Select employment type',
            type: 'select',
            options: 'employment_type',
            description: 'Type of employment',
            showInTable: false,
            showInForm: true,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'employment_type',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'employment',
        },
        employment_type_name: {
            label: 'Employment Type',
            placeholder: 'Select employment type',
            type: 'select',
            options: 'employment_type',
            description: 'Type of employment',
            showInTable: true,
            showInForm: false,
            tableWidth: '140px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'employment_type',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'employment',
        },
        employment_date: {
            label: 'Employment Date',
            type: 'date',
            description: 'Date of employment start',
            showInTable: false,
            showInForm: true,
            tableWidth: '120px',
            tableFormat: function(value) {
                if (!value) return '';
                var date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'employment',
        },
        job_title: {
            label: 'Job Title',
            placeholder: 'Software Engineer',
            type: 'text',
            description: 'Current job title',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'employment',
        },
        department_id: {
            label: 'Department',
            placeholder: 'Select department',
            type: 'select',
            required: true,
            options: 'departments',
            description: 'Department the user belongs to',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'departments',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        department_name: {
            label: 'Department',
            type: 'select',
            required: true,
            options: 'departments',
            description: 'Department the user belongs to',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'departments',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'department',
        },
        role_id: {
            label: 'role',
            placeholder: 'Select role',
            type: 'select',
            required: true,
            options: 'roles',
            description: 'role the user belongs to',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'roles',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'role',
        },
        role_name: {
            label: 'Role',
            type: 'select',
            required: true,
            options: 'roles',
            description: 'role the user belongs to',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'roles',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'role',
        },
        location_id: {
            label: 'location',
            placeholder: 'Select location',
            type: 'select',
            required: true,
            options: 'locations',
            description: 'location the user belongs to',
            showInTable: false,
            showInForm: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        },
        location_name: {
            label: 'location',
            type: 'select',
            options: 'Locations',
            description: 'location the user belongs to',
            showInTable: true,
            showInForm: false,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'locations',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'location',
        }, 
        


        // ==================== STATUS ====================
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            hidden:true,
            description: 'Whether the user account is active',
            showInTable: false,
            showInForm: true,
            tableWidth: '80px',
            tableFormat: function(value) {
                return value ? '✅' : '❌';
            },
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        last_login_at: {
            label: 'Last Login',
            type: 'datetime',
            hidden:true,
            disabled: true,
            description: 'Last login timestamp',
            showInTable: false,
            showInForm: false,
            tableWidth: '150px',
            tableFormat: function(value) {
                if (!value) return 'Never';
                var date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },

        // ==================== AUDIT ====================
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            hidden:true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            tableWidth: '150px',
            tableFormat: function(value) {
                if (!value) return '';
                var date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        updated_at: {
            label: 'Updated Date',
            type: 'datetime',
            hidden:true,
            disabled: true,
            showInTable: false,
            showInForm: false,
            filterable: false,
            analyzable: false,
        },
    },
};

export default users;