const vendors = {
    frontendRoutes: ['/procurement/vendors'],
    description: 'Vendor/Supplier information',
    form: 'VendorForm',
    tableName: 'vendors',
    displayName: 'Vendors',
    grp:8,
    groupid:8,
    icon: 'Building',
    defaultSort: { field: 'company_name', direction: 'ASC' },
    defaultFilters: { is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'payment_terms',
        defaultMetric: 'total_purchases',
        chartTypes: ['bar', 'pie', 'table', 'scatter'],
        availableMetrics: ['count', 'total_purchases', 'credit_limit', 'avg_purchase'],
        availableDimensions: ['payment_terms', 'is_active', 'company_name'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Vendor Code',
            placeholder: 'VEN-001',
            type: 'text',
            required: true,
            description: 'Unique vendor identifier',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Company Name',
            placeholder: 'Acme Corp',
            type: 'text',
            required: true,
            description: 'Vendor company name',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'vendor',
        },
        text_1: {
            label: 'Contact Person',
            placeholder: 'John Smith',
            type: 'text',
            description: 'Primary contact person at vendor',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        text_2: {
            label: 'Email',
            placeholder: 'vendor@company.com',
            type: 'email',
            description: 'Vendor contact email',
            icon: 'EnvelopeIcon',
            showInTable: true,
            tableWidth: '200px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
            validation: {
                pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
                message: 'Please enter a valid email address',
            },
        },
        text_3: {
            label: 'Phone',
            placeholder: '+1 (555) 000-0000',
            type: 'phone',
            description: 'Vendor contact phone number',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        comment1: {
            label: 'Address',
            placeholder: '123 Vendor Street',
            type: 'textarea',
            description: 'Vendor physical address',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            description: 'Whether the vendor is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            type: 'datetime',
            hidden: true,
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default vendors;