// src/config/users/workflows.ts
const workflows = {
    frontendRoutes: ['/settings/workflows', '/admin/workflows'],
    description: 'Configure approval workflows for different document types',
    form: 'WorkflowForm',
    tableName: 'commons',
    groupid: 20,
    grp: 20,
    displayName: 'Approval Workflows',
    icon: 'GitBranch',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 20, is_active: true },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
        },
        code: {
            label: 'Workflow Code',
            placeholder: 'REQ_STD',
            type: 'text',
            required: true,
            description: 'Unique workflow code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
        },
        name: {
            label: 'Workflow Name',
            placeholder: 'Standard Requisition',
            type: 'text',
            required: true,
            description: 'Display name for the workflow',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Description of this workflow',
            showInTable: true,
            tableWidth: '200px',
            filterable: false,
        },
        text_1: {
            label: 'Max Amount',
            type: 'number',
            step: 0.01,
            default: 0,
            description: 'Maximum amount for this workflow (0 = unlimited)',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => value === 0 ? 'Unlimited' : `${Number(value).toLocaleString()}`,
            filterable: true,
            filterType: 'number',
        },
        item_id1: {
            label: 'Document Type',
            placeholder: 'Select document type',
            type: 'select',
            options: 'requisition_types',
            filterOptions: { grp: 10 },
            description: 'Which document type uses this workflow',
            showInTable: false,
            shoInFoem:true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'reqisition_types',
        },
        item_name1: {
            label: 'Document Type',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
        },
        item_id2: {
            label: 'Workflow Type',
            placeholder: 'Select workflow type',
            type: 'select',
            options: 'workflowtypes',
            filterOptions: { grp: 15 },
            description: 'Type of workflow ',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'workflowtypes',
        },
        item_name2: {
            label: 'Workflow Type',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            hidden:true,
            description: 'Whether this workflow is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
        },
    },
};

export default workflows;