// src/config/workflowtypes/workflowtypes.ts
const workflowtypes = {
    frontendRoutes: ['/settings/workflow-types', '/workflows/types'],
    description: 'Types of workflow patterns (serial, parallel, hybrid)',
    form: 'WorkflowTypeForm',
    tableName: 'commons',
    groupid: 15,
    grp: 15,
    displayName: 'Workflow Types',
    icon: 'GitBranch',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 15, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'is_active',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Workflow Type Code',
            placeholder: 'SERIAL',
            type: 'text',
            required: true,
            description: 'Unique workflow type code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Workflow Type Name',
            placeholder: 'Serial Approval',
            type: 'text',
            required: true,
            description: 'Display name for the workflow type',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'workflow_type',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'Description of this workflow pattern',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this workflow type is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default workflowtypes;