// src/config/users/workflowsteps.ts
const workflowsteps = {
    frontendRoutes: ['/settings/workflow-steps', '/admin/workflow-steps'],
    description: 'Configure individual steps within workflows',
    form: 'WorkflowStepForm',
    tableName: 'commons',
    groupid: 21,
    grp: 21,
    displayName: 'Workflow Steps',
    icon: 'StepForward',
    defaultSort: { field: 'item_id2', direction: 'ASC' },
    defaultFilters: { grp: 21, is_active: true },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
        },
        parent_id: {
            label: 'Workflow',
            hidden: true,
            placeholder: 'Select Workflow',
            type: 'select',
            options: 'roles',
            filterOptions: { grp: 20 },
            required: true,
            description: 'Workflow this step belongs to',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'roles',
        },
        parent_name: {
            label: 'Workflow Name',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
        },
        code: {
            label: 'Step Code',
            placeholder: 'STEP_1',
            type: 'text',
            required: true,
            description: 'Unique step code within workflow',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'text',
        },
        name: {
            label: 'Step Name',
            placeholder: 'Line Manager Approval',
            type: 'text',
            required: true,
            description: 'Display name for the step',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            showInTable: true,
            description: 'What this step requires',
        },
        item_id1: {
            label: 'Role',
            placeholder: 'Select Role',
            type: 'select',
            options: 'roles',
            filterOptions: { grp: 1 },
            required: true,
            description: 'Role that approves this step',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'roles',
        },
        item_name1: {
            label: 'Role Name',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
        },
        item_id2: {
            label: 'Serial Number',
            type: 'number',
            required: true,
            default: 1,
            description: 'Approval order (1 = first, highest = final)',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        item_id3: {
            label: 'Expected Days',
            type: 'number',
            default: 3,
            description: 'Expected response time in days',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        text_3: {
            label: 'Mandatory',
            type: 'toggle',
            hidden: true,
            default: true,
            description: 'Must this step be completed to proceed?',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order within workflow',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        is_active: {
            label: 'Active',
            type: 'toggle',
            default: true,
            description: 'Whether this step is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            hidden: true,
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
        },
    },
};

export default workflowsteps;