// src/config/workflowstatus/workflowstatus.ts
const workflowstatus = {
    frontendRoutes: ['/settings/workflow-status', '/workflows/status'],
    description: 'Status values for workflow instances',
    form: 'WorkflowstatusForm',
    tableName: 'commons',
    groupid: 11,
    grp: 11,
    displayName: 'Workflow Status',
    icon: 'Activity',
    defaultSort: { field: 'sort_order', direction: 'ASC' },
    defaultFilters: { grp: 11, is_active: true },
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'bool_1',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['bool_1', 'is_active', 'code'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        grp: {
            label: 'grp',
            type: 'number',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        code: {
            label: 'Status Code',
            placeholder: 'APPROVED',
            type: 'text',
            required: true,
            description: 'Unique status code',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'text',
            analyzable: false,
        },
        name: {
            label: 'Status Name',
            placeholder: 'Approved',
            type: 'text',
            required: true,
            description: 'Display name for the status',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        comment1: {
            label: 'Description',
            placeholder: '...',
            type: 'textarea',
            description: 'What this status means',
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
        },
        text_1: {
            label: 'Color Code',
            placeholder: '#4A90D9',
            type: 'color',
            description: 'Color for UI display',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => `<span style="color:${value}">●</span> ${value}`,
            filterable: false,
            analyzable: false,
        },
        text_2: {
            label: 'Icon Class',
            placeholder: 'fa-check-circle',
            type: 'text',
            description: 'Font Awesome icon class',
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        bool_1: {
            label: 'Is Terminal',
            type: 'toggle',
            default: false,
            description: 'Is this a final/end state?',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status_type',
        },
        item_id1: {
            label: 'Priority Level',
            placeholder: 'Select priority',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 14 },
            description: 'Priority level for this status',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_14',
            analyzable: false,
        },
        item_name1: {
            label: 'Priority Name',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
            analyzable: false,
            // This will be populated via JOIN with commons
        },
        sort_order: {
            label: 'Sort Order',
            type: 'number',
            default: 0,
            description: 'Display order',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        is_active: {
            label: 'Active',
            hidden: true,
            type: 'toggle',
            default: true,
            description: 'Whether this status is active',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '✅' : '❌',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        created_at: {
            label: 'Created Date',
            hidden: true,
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
    },
};

export default workflowstatus;