// src/config/purchase_requisitions/workflowinstances.ts
const workflowinstances = {
    frontendRoutes: ['/workflows/instances', '/approvals/pending'],
    description: 'Track and manage workflow instances',
    form: 'WorkflowInstanceForm',
    tableName: 'workflowinstances',
    displayName: 'Workflow Instances',
    icon: 'GitPullRequest',
    defaultSort: { field: 'submitted_at', direction: 'DESC' },
    defaultFilters: { status_id: 2 }, // Default to PENDING
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'status_id',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count'],
        availableDimensions: ['status_id', 'document_type_id', 'priority_id'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
        },
        workflow_id: {
            label: 'Workflow',
            placeholder: 'Select workflow',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 20 },
            required: true,
            description: 'Workflow definition to use',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_20',
        },
        document_type_id: {
            label: 'Document Type',
            placeholder: 'Select document type',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 10 },
            required: true,
            description: 'Type of document being processed',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_10',
        },
        document_id: {
            label: 'Document ID',
            type: 'number',
            required: true,
            description: 'ID of the document in its table',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        document_number: {
            label: 'Document Number',
            type: 'text',
            placeholder: 'REQ-2026-001',
            description: 'Human-readable document number',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'text',
        },
        status_id: {
            label: 'Status',
            placeholder: 'Select status',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 11 },
            required: true,
            description: 'Current workflow status',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_11',
        },
        priority_id: {
            label: 'Priority',
            placeholder: 'Select priority',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 14 },
            default: 2,
            description: 'Priority level',
            showInTable: true,
            tableWidth: '120px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_14',
        },
        submitted_by: {
            label: 'Submitted By',
            type: 'select',
            options: 'users',
            required: true,
            description: 'User who submitted the request',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
        },
        submitted_at: {
            label: 'Submitted At',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
        },
        last_activity_at: {
            label: 'Last Activity',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
        },
        approved_at: {
            label: 'Approved At',
            type: 'datetime',
            disabled: true,
            showInTable: false,
        },
        rejected_at: {
            label: 'Rejected At',
            type: 'datetime',
            disabled: true,
            showInTable: false,
        },
        completed_at: {
            label: 'Completed At',
            type: 'datetime',
            disabled: true,
            showInTable: false,
        },
        escalation_count: {
            label: 'Escalations',
            type: 'number',
            default: 0,
            description: 'Number of times escalated',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
        },
        comments: {
            label: 'Comments',
            type: 'textarea',
            description: 'General comments about this instance',
            showInTable: false,
        },
        metadata: {
            label: 'Metadata',
            type: 'json',
            description: 'Additional structured data',
            showInTable: false,
        },
        created_at: {
            label: 'Created',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
        },
    },
};

export default workflowinstances;