// src/config/purchase_requisitions/workflowinstancesteps.ts

const workflowinstancesteps = {
    frontendRoutes: ['/workflows/instances/steps', '/approvals/steps', '/workflows/tracking'],
    description: 'Track individual steps within workflow instances',
    form: 'WorkflowInstanceStepForm',
    tableName: 'workflow_instance_steps',
    displayName: 'Workflow Instance Steps',
    icon: 'StepForward',
    defaultSort: { field: 'step_serial_number', direction: 'ASC' },
    defaultFilters: { status_id: 2 }, // Default to PENDING
    analysisConfig: {
        enabled: true,
        defaultGroupBy: 'status_id',
        defaultMetric: 'count',
        chartTypes: ['bar', 'pie', 'table', 'line'],
        availableMetrics: ['count', 'actual_days', 'expected_days'],
        availableDimensions: ['status_id', 'role_id', 'step_id', 'is_overdue'],
    },
    fields: {
        id: {
            label: 'ID',
            type: 'text',
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: false,
        },
        instance_id: {
            label: 'Instance ID',
            type: 'number',
            required: true,
            description: 'Workflow instance this step belongs to',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: false,
        },
        // Virtual field for displaying instance info
        instance_info: {
            label: 'Instance',
            type: 'text',
            hidden: true,
            showInTable: true,
            tableWidth: '180px',
            filterable: false,
            analyzable: false,
            // This will be populated via JOIN
        },
        step_id: {
            label: 'Step',
            placeholder: 'Select step',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 21 },
            required: true,
            description: 'Step definition from workflow',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_21',
            analyzable: false,
        },
        step_name: {
            label: 'Step Name',
            type: 'text',
            disabled: true,
            description: 'Name of the step',
            showInTable: true,
            tableWidth: '180px',
            filterable: true,
            filterType: 'text',
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'step',
        },
        step_serial_number: {
            label: 'Serial #',
            type: 'number',
            disabled: true,
            description: 'Step order number in workflow',
            showInTable: true,
            tableWidth: '80px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        role_id: {
            label: 'Role',
            placeholder: 'Select role',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 1 },
            required: true,
            description: 'Role responsible for this step',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_1',
            analyzable: false,
        },
        role_name: {
            label: 'Role Name',
            type: 'text',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'role',
        },
        assigned_to_user_id: {
            label: 'Assigned To',
            placeholder: 'Select user',
            type: 'select',
            options: 'users',
            description: 'User assigned to approve this step',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: false,
        },
        assigned_user_name: {
            label: 'Assigned User',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'user',
        },
        assigned_at: {
            label: 'Assigned At',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        status_id: {
            label: 'Status',
            placeholder: 'Select status',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 11 },
            required: true,
            description: 'Current status of this step',
            showInTable: true,
            tableWidth: '130px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_11',
            analyzable: false,
        },
        status_name: {
            label: 'Status Name',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '130px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
        started_at: {
            label: 'Started At',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        completed_at: {
            label: 'Completed At',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        action_id: {
            label: 'Action',
            placeholder: 'Select action',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 12 },
            description: 'Action taken on this step',
            showInTable: true,
            tableWidth: '130px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_12',
            analyzable: false,
        },
        action_name: {
            label: 'Action Name',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '130px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'action',
        },
        performed_by: {
            label: 'Performed By',
            type: 'select',
            options: 'users',
            description: 'User who performed the action',
            showInTable: true,
            tableWidth: '150px',
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: false,
        },
        performed_by_name: {
            label: 'Performer',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '150px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'user',
        },
        comments: {
            label: 'Comments',
            type: 'textarea',
            description: 'Comments for this step',
            showInTable: false,
            analyzable: false,
        },
        escalated_from_user_id: {
            label: 'Escalated By',
            type: 'select',
            options: 'users',
            description: 'User who escalated this step',
            showInTable: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'users',
            analyzable: false,
        },
        escalated_at: {
            label: 'Escalated At',
            type: 'datetime',
            disabled: true,
            showInTable: false,
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        escalation_reason_id: {
            label: 'Escalation Reason',
            placeholder: 'Select reason',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 17 },
            description: 'Reason for escalation',
            showInTable: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_17',
            analyzable: false,
        },
        escalation_reason_name: {
            label: 'Escalation Reason',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'reason',
        },
        escalation_comments: {
            label: 'Escalation Comments',
            type: 'textarea',
            description: 'Additional escalation details',
            showInTable: false,
            analyzable: false,
        },
        rejection_reason_id: {
            label: 'Rejection Reason',
            placeholder: 'Select reason',
            type: 'select',
            options: 'commons',
            filterOptions: { grp: 18 },
            description: 'Reason for rejection',
            showInTable: false,
            filterable: true,
            filterType: 'select',
            filterOptions: 'commons_18',
            analyzable: false,
        },
        rejection_reason_name: {
            label: 'Rejection Reason',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: false,
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'reason',
        },
        rejection_comments: {
            label: 'Rejection Comments',
            type: 'textarea',
            description: 'Additional rejection details',
            showInTable: false,
            analyzable: false,
        },
        expected_days: {
            label: 'Expected Days',
            type: 'number',
            default: 3,
            description: 'Expected response time in days',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        actual_days: {
            label: 'Actual Days',
            type: 'number',
            disabled: true,
            description: 'Actual days taken to complete',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        due_date: {
            label: 'Due Date',
            type: 'date',
            description: 'Calculated due date',
            showInTable: true,
            tableWidth: '120px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleDateString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        is_overdue: {
            label: 'Overdue',
            type: 'toggle',
            disabled: true,
            description: 'Whether this step is overdue',
            showInTable: true,
            tableWidth: '80px',
            tableFormat: (value) => value ? '🔴' : '✅',
            filterable: true,
            filterType: 'boolean',
            filterOptions: 'yes_no',
            analyzable: true,
            analysisType: 'percentage',
            analysisGroup: 'status',
        },
        reminded_count: {
            label: 'Reminders',
            type: 'number',
            default: 0,
            description: 'Number of reminders sent',
            showInTable: true,
            tableWidth: '100px',
            filterable: true,
            filterType: 'number',
            analyzable: true,
            analysisType: 'measure',
        },
        last_reminded_at: {
            label: 'Last Reminded',
            type: 'datetime',
            disabled: true,
            showInTable: false,
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        created_at: {
            label: 'Created',
            type: 'datetime',
            disabled: true,
            showInTable: true,
            tableWidth: '150px',
            tableFormat: (value) => {
                if (!value) return '';
                const date = new Date(value);
                return date.toLocaleString();
            },
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        updated_at: {
            label: 'Updated',
            type: 'datetime',
            disabled: true,
            showInTable: false,
            filterable: true,
            filterType: 'date',
            analyzable: true,
            analysisType: 'trend',
            analysisGroup: 'activity',
        },
        // Calculated/virtual fields
        step_phase: {
            label: 'Step Phase',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '130px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'phase',
        },
        days_pending: {
            label: 'Days Pending',
            type: 'number',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '100px',
            filterable: false,
            analyzable: true,
            analysisType: 'measure',
        },
        step_status: {
            label: 'Step Status',
            type: 'text',
            disabled: true,
            hidden: true,
            showInTable: true,
            tableWidth: '120px',
            filterable: false,
            analyzable: true,
            analysisType: 'group',
            analysisGroup: 'status',
        },
    },
};

export default workflowinstancesteps;