// src/types/auth.js

export const AUTH_TYPES = {
    // Login
    LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'AUTH_LOGIN_FAILURE',
    SWITCH_LOCATION_SUCCESS: 'AUTH_SWITCH_LOCATION_SUCCESS',
    SWITCH_ROLE_SUCCESS: 'AUTH_SWITCH_ROLE_SUCCESS',
    
    // Admin Login
    ADMIN_LOGIN_REQUEST: 'AUTH_ADMIN_LOGIN_REQUEST',
    ADMIN_LOGIN_SUCCESS: 'AUTH_ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAILURE: 'AUTH_ADMIN_LOGIN_FAILURE',
    
    
    // Tenant Login
    TENANT_LOGIN_REQUEST: 'AUTH_TENANT_LOGIN_REQUEST',
    TENANT_LOGIN_SUCCESS: 'AUTH_TENANT_LOGIN_SUCCESS',
    TENANT_LOGIN_FAILURE: 'AUTH_TENANT_LOGIN_FAILURE',
    
    // Register
    REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'AUTH_REGISTER_FAILURE',
    
    // Logout
    LOGOUT: 'AUTH_LOGOUT',
    
    // Session
    CHECK_AUTH: 'AUTH_CHECK_AUTH',
    SET_LOADING: 'AUTH_SET_LOADING',
    CLEAR_ERROR: 'AUTH_CLEAR_ERROR',
    REFRESH_TOKEN: 'AUTH_REFRESH_TOKEN',
    
    // Permissions
    SET_PERMISSIONS: 'AUTH_SET_PERMISSIONS',
    UPDATE_USER: 'AUTH_UPDATE_USER',
    SET_USER_TYPE: 'AUTH_SET_USER_TYPE',
};

export const USER_TYPES = {
    ADMIN: 'admin',
    TENANT: 'tenant',
    GUEST: 'guest',
};

export const LOGIN_TYPES = {
    ADMIN: 'login_admin',
    TENANT: 'login_tenant',
    GOOGLE: 'login_google',
    X: 'login_x',
};