const OPTION_DATA: Record<string, Array<{ value: any; label: string }>> = {
    // Identity & Access
    departments: [
        { value: 'finance', label: 'Finance' },
        { value: 'hr', label: 'Human Resources' },
        { value: 'it', label: 'IT' },
        { value: 'operations', label: 'Operations' },
        { value: 'sales', label: 'Sales' },
        { value: 'marketing', label: 'Marketing' },
        { value: 'procurement', label: 'Procurement' },
        { value: 'legal', label: 'Legal' },
        { value: 'rnd', label: 'R&D' },
    ],
    roles: [
        { value: 'super_admin', label: 'Super Admin' },
        { value: 'admin', label: 'Admin' },
        { value: 'finance_manager', label: 'Finance Manager' },
        { value: 'department_head', label: 'Department Head' },
        { value: 'line_manager', label: 'Line Manager' },
        { value: 'procurement_officer', label: 'Procurement Officer' },
        { value: 'employee', label: 'Employee' },
        { value: 'viewer', label: 'Viewer' },
    ],
    users: [
        { value: '1', label: 'John Doe' },
        { value: '2', label: 'Jane Smith' },
        { value: '3', label: 'Bob Johnson' },
        { value: '4', label: 'Alice Williams' },
        { value: '5', label: 'Charlie Brown' },
    ],
    locations: [
        { value: 'lagos', label: 'Lagos, Nigeria' },
        { value: 'abuja', label: 'Abuja, Nigeria' },
        { value: 'port_harcourt', label: 'Port Harcourt, Nigeria' },
        { value: 'new_york', label: 'New York, USA' },
        { value: 'london', label: 'London, UK' },
        { value: 'dubai', label: 'Dubai, UAE' },
    ],
    vendors: [
        { value: '1', label: 'Acme Corp' },
        { value: '2', label: 'Tech Solutions' },
        { value: '3', label: 'Global Services' },
        { value: '4', label: 'Office Supplies Ltd' },
        { value: '5', label: 'IT Hardware Inc' },
    ],
    skus: [
        { value: '1', label: 'HP Laptop - ProBook' },
        { value: '2', label: 'Dell Monitor - 27"' },
        { value: '3', label: 'Office Chair - Ergonomic' },
        { value: '4', label: 'Keyboard - Wireless' },
        { value: '5', label: 'Mouse - Bluetooth' },
    ],
    item_categories: [
        { value: '1', label: 'Office Supplies' },
        { value: '2', label: 'IT Equipment' },
        { value: '3', label: 'Furniture' },
        { value: '4', label: 'Vehicles' },
        { value: '5', label: 'Maintenance Supplies' },
        { value: '6', label: 'Software' },
        { value: '7', label: 'Services' },
        { value: '8', label: 'Machinery' },
    ],
    purchase_orders: [
        { value: '1', label: 'PO-2026-001' },
        { value: '2', label: 'PO-2026-002' },
        { value: '3', label: 'PO-2026-003' },
        { value: '4', label: 'PO-2026-004' },
        { value: '5', label: 'PO-2026-005' },
    ],
    purchase_requisitions: [
        { value: '1', label: 'PR-2026-001' },
        { value: '2', label: 'PR-2026-002' },
        { value: '3', label: 'PR-2026-003' },
        { value: '4', label: 'PR-2026-004' },
        { value: '5', label: 'PR-2026-005' },
    ],
    invoices: [
        { value: '1', label: 'INV-2026-001' },
        { value: '2', label: 'INV-2026-002' },
        { value: '3', label: 'INV-2026-003' },
        { value: '4', label: 'INV-2026-004' },
        { value: '5', label: 'INV-2026-005' },
    ],
    cash_advances: [
        { value: '1', label: 'ADV-2026-001' },
        { value: '2', label: 'ADV-2026-002' },
        { value: '3', label: 'ADV-2026-003' },
        { value: '4', label: 'ADV-2026-004' },
        { value: '5', label: 'ADV-2026-005' },
    ],
    grns: [
        { value: '1', label: 'GRN-2026-001' },
        { value: '2', label: 'GRN-2026-002' },
        { value: '3', label: 'GRN-2026-003' },
        { value: '4', label: 'GRN-2026-004' },
        { value: '5', label: 'GRN-2026-005' },
    ],
    po_items: [
        { value: '1', label: 'PO Item 1' },
        { value: '2', label: 'PO Item 2' },
        { value: '3', label: 'PO Item 3' },
        { value: '4', label: 'PO Item 4' },
        { value: '5', label: 'PO Item 5' },
    ],
    fixed_assets: [
        { value: '1', label: 'AST-001 - Dell Laptop' },
        { value: '2', label: 'AST-002 - HP Server' },
        { value: '3', label: 'AST-003 - Office Chair' },
        { value: '4', label: 'AST-004 - Toyota Camry' },
        { value: '5', label: 'AST-005 - Printer' },
    ],
    workflow_steps: [
        { value: '1', label: 'Step 1 - Manager Approval' },
        { value: '2', label: 'Step 2 - Finance Approval' },
        { value: '3', label: 'Step 3 - Final Approval' },
        { value: '4', label: 'Step 4 - Procurement Review' },
        { value: '5', label: 'Step 5 - Director Approval' },
    ],
    approval_workflows: [
        { value: '1', label: 'Purchase Workflow' },
        { value: '2', label: 'Expense Workflow' },
        { value: '3', label: 'Invoice Workflow' },
        { value: '4', label: 'Advance Workflow' },
        { value: '5', label: 'GRN Workflow' },
    ],
    requisition_types: [
        { value: 'goods', label: 'Goods' },
        { value: 'service', label: 'Service' },
        { value: 'cash_advance', label: 'Cash Advance' },
    ],
    payment_terms: [
        { value: 'net15', label: 'Net 15' },
        { value: 'net30', label: 'Net 30' },
        { value: 'net45', label: 'Net 45' },
        { value: 'net60', label: 'Net 60' },
        { value: 'on_delivery', label: 'On Delivery' },
        { value: 'advance', label: 'Advance' },
    ],
    priorities: [
        { value: 'low', label: 'Low' },
        { value: 'medium', label: 'Medium' },
        { value: 'high', label: 'High' },
        { value: 'urgent', label: 'Urgent' },
        { value: 'critical', label: 'Critical' },
    ],
    authority_levels: [
        { value: 1, label: 'Level 1 - Basic' },
        { value: 3, label: 'Level 3 - Team Lead' },
        { value: 5, label: 'Level 5 - Department Head' },
        { value: 8, label: 'Level 8 - Finance Manager' },
        { value: 10, label: 'Level 10 - Super Admin' },
    ],
    tax_rates: [
        { value: 0, label: '0%' },
        { value: 5, label: '5%' },
        { value: 7.5, label: '7.5%' },
        { value: 10, label: '10%' },
        { value: 15, label: '15%' },
        { value: 20, label: '20%' },
        { value: 25, label: '25%' },
    ],
    payment_methods: [
        { value: 'bank_transfer', label: 'Bank Transfer' },
        { value: 'cheque', label: 'Cheque' },
        { value: 'cash', label: 'Cash' },
        { value: 'credit_card', label: 'Credit Card' },
        { value: 'debit_card', label: 'Debit Card' },
        { value: 'mobile_money', label: 'Mobile Money' },
        { value: 'crypto', label: 'Cryptocurrency' },
    ],
    entity_types: [
        { value: 'requisition', label: 'Requisition' },
        { value: 'invoice', label: 'Invoice' },
        { value: 'payment', label: 'Payment' },
        { value: 'grn', label: 'GRN' },
        { value: 'retirement', label: 'Retirement' },
        { value: 'purchase_order', label: 'Purchase Order' },
        { value: 'advance', label: 'Advance' },
    ],
    account_types: [
        { value: 'asset', label: 'Asset' },
        { value: 'liability', label: 'Liability' },
        { value: 'equity', label: 'Equity' },
        { value: 'income', label: 'Income' },
        { value: 'expense', label: 'Expense' },
        { value: 'contra_asset', label: 'Contra Asset' },
    ],
    units: [
        { value: 'each', label: 'Each' },
        { value: 'kg', label: 'Kilogram' },
        { value: 'g', label: 'Gram' },
        { value: 'l', label: 'Liter' },
        { value: 'm', label: 'Meter' },
        { value: 'cm', label: 'Centimeter' },
        { value: 'box', label: 'Box' },
        { value: 'pack', label: 'Pack' },
        { value: 'set', label: 'Set' },
        { value: 'pair', label: 'Pair' },
    ],
    conditions: [
        { value: 'new', label: 'New' },
        { value: 'good', label: 'Good' },
        { value: 'fair', label: 'Fair' },
        { value: 'poor', label: 'Poor' },
        { value: 'disposed', label: 'Disposed' },
        { value: 'damaged', label: 'Damaged' },
        { value: 'under_repair', label: 'Under Repair' },
    ],
    requisition_status: [
        { value: 'draft', label: 'Draft' },
        { value: 'pending_approval', label: 'Pending Approval' },
        { value: 'approved', label: 'Approved' },
        { value: 'rejected', label: 'Rejected' },
        { value: 'converted_to_po', label: 'Converted to PO' },
        { value: 'closed', label: 'Closed' },
        { value: 'cancelled', label: 'Cancelled' },
    ],
    po_status: [
        { value: 'draft', label: 'Draft' },
        { value: 'sent', label: 'Sent' },
        { value: 'partially_received', label: 'Partially Received' },
        { value: 'fully_received', label: 'Fully Received' },
        { value: 'invoiced', label: 'Invoiced' },
        { value: 'paid', label: 'Paid' },
        { value: 'cancelled', label: 'Cancelled' },
    ],
    grn_status: [
        { value: 'draft', label: 'Draft' },
        { value: 'pending_review', label: 'Pending Review' },
        { value: 'approved', label: 'Approved' },
        { value: 'rejected', label: 'Rejected' },
        { value: 'partially_approved', label: 'Partially Approved' },
    ],
    invoice_status: [
        { value: 'received', label: 'Received' },
        { value: 'verified', label: 'Verified' },
        { value: 'approved', label: 'Approved' },
        { value: 'paid', label: 'Paid' },
        { value: 'overdue', label: 'Overdue' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'disputed', label: 'Disputed' },
    ],
    payment_status: [
        { value: 'initiated', label: 'Initiated' },
        { value: 'processing', label: 'Processing' },
        { value: 'completed', label: 'Completed' },
        { value: 'failed', label: 'Failed' },
        { value: 'reversed', label: 'Reversed' },
        { value: 'pending_approval', label: 'Pending Approval' },
    ],
    advance_status: [
        { value: 'approved', label: 'Approved' },
        { value: 'disbursed', label: 'Disbursed' },
        { value: 'partially_retired', label: 'Partially Retired' },
        { value: 'fully_retired', label: 'Fully Retired' },
        { value: 'overdue', label: 'Overdue' },
        { value: 'cancelled', label: 'Cancelled' },
    ],
    retirement_status: [
        { value: 'pending_verification', label: 'Pending Verification' },
        { value: 'verified', label: 'Verified' },
        { value: 'approved', label: 'Approved' },
        { value: 'rejected', label: 'Rejected' },
        { value: 'partially_approved', label: 'Partially Approved' },
    ],
    approval_status: [
        { value: 'pending', label: 'Pending' },
        { value: 'approved', label: 'Approved' },
        { value: 'rejected', label: 'Rejected' },
        { value: 'escalated', label: 'Escalated' },
        { value: 'deferred', label: 'Deferred' },
    ],
    audit_actions: [
        { value: 'create', label: 'Create' },
        { value: 'update', label: 'Update' },
        { value: 'delete', label: 'Delete' },
        { value: 'approve', label: 'Approve' },
        { value: 'reject', label: 'Reject' },
        { value: 'view', label: 'View' },
        { value: 'login', label: 'Login' },
        { value: 'logout', label: 'Logout' },
        { value: 'system', label: 'System' },
        { value: 'export', label: 'Export' },
        { value: 'import', label: 'Import' },
    ],
    subscription_plans: [
        { value: 'free', label: 'Free' },
        { value: 'basic', label: 'Basic' },
        { value: 'professional', label: 'Professional' },
        { value: 'enterprise', label: 'Enterprise' },
        { value: 'premium', label: 'Premium' },
    ],
    subscription_statuses: [
        { value: 'active', label: 'Active' },
        { value: 'trial', label: 'Trial' },
        { value: 'suspended', label: 'Suspended' },
        { value: 'expired', label: 'Expired' },
        { value: 'cancelled', label: 'Cancelled' },
        { value: 'pending', label: 'Pending' },
    ],
    billing_cycles: [
        { value: 'monthly', label: 'Monthly' },
        { value: 'quarterly', label: 'Quarterly' },
        { value: 'semi_annual', label: 'Semi-Annual' },
        { value: 'annual', label: 'Annual' },
        { value: 'one_time', label: 'One Time' },
    ],
    depreciation_methods: [
        { value: 'straight_line', label: 'Straight Line' },
        { value: 'declining_balance', label: 'Declining Balance' },
        { value: 'units_of_production', label: 'Units of Production' },
        { value: 'sum_of_years', label: 'Sum of Years' },
        { value: 'double_declining', label: 'Double Declining' },
    ],
    currencies: [
        { value: 'USD', label: 'USD - US Dollar' },
        { value: 'EUR', label: 'EUR - Euro' },
        { value: 'GBP', label: 'GBP - British Pound' },
        { value: 'NGN', label: 'NGN - Nigerian Naira' },
        { value: 'KES', label: 'KES - Kenyan Shilling' },
        { value: 'ZAR', label: 'ZAR - South African Rand' },
        { value: 'CAD', label: 'CAD - Canadian Dollar' },
        { value: 'AUD', label: 'AUD - Australian Dollar' },
        { value: 'JPY', label: 'JPY - Japanese Yen' },
        { value: 'CNY', label: 'CNY - Chinese Yuan' },
    ],
    yes_no: [
        { value: true, label: 'Yes' },
        { value: false, label: 'No' },
    ],
    // Gender
    gender: [
        { value: 'male', label: 'Male' },
        { value: 'female', label: 'Female' },
        { value: 'other', label: 'Other' },
    ],
    // Marital Status
    marital_status: [
        { value: 'single', label: 'Single' },
        { value: 'married', label: 'Married' },
        { value: 'divorced', label: 'Divorced' },
        { value: 'widowed', label: 'Widowed' },
    ],
    // Employment Type
    employment_type: [
        { value: 'full_time', label: 'Full Time' },
        { value: 'part_time', label: 'Part Time' },
        { value: 'contract', label: 'Contract' },
        { value: 'intern', label: 'Intern' },
        { value: 'freelance', label: 'Freelance' },
    ],
};

export default OPTION_DATA;